### ISSUE TITLE
Orientation distributions seem to depend on initial angle (Trac #1072)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1127]
Reported by Patrick Corona.

The perfectly oriented calculations (i.e. no orientation distributions) now match what we were calculating. Also, importing data for fitting works for us, and we are excited by the potential this offers to compare and fit to models of oriented structures.

We do run into some issues as we begin to apply orientation distributions that I will highlight with the ‘stock’ spectra prediction calculator. As we apply orientation distributions with the array utility, the results tend to depend on the initial angle one sets, even for a uniform distribution.

For example, if I apply the uniform distribution (attached as uniform.txt) to the parallelepiped model in both theta and psi directions (i.e. equivalent weighting to all out of plane and c-axis rotation angles with one in-plane direction evaluated) the results do not match our predictions for what a parallelepiped oriented at 60 deg in plane should look like (Note: length and scale parameters are just what are provided initially for the model):

corona-fig-1.png

If I change the theta and psi angles – which I would not expect would change anything because I have imported a custom distribution – I can get some drastic changes to the spectra, eventually leading to a similar spectra to what we have predicted with our own code:

corona-fig-2.png

Our initial hypothesis was that changing these angles changes the initial angle the distribution is evaluated at, but this doesn’t make sense for the uniform distribution we are testing here. Have we set up the array wrong? I’ve also tried an array that runs from 0 to 360 degrees, but that doesn’t change anything. Additionally, the results get more confusing with non-uniform distributions, and I will not go into details on those unless it can be helpful to solving this problem – I think that fixing whatever is causing this will fix those problems we are having too.

Let me know if I can provide more information from what we have been seeing with the non-uniform distributions (if the solution is not obvious).

Migrated from http://trac.sasview.org/ticket/1072
```json
{
    "status": "closed",
    "changetime": "2018-07-21T19:15:31",
    "_ts": "2018-07-21 19:15:31.146576+00:00",
    "description": "Reported by Patrick Corona.\n\nThe perfectly oriented calculations (i.e. no orientation distributions) now match what we were calculating. Also, importing data for fitting works for us, and we are excited by the potential this offers to compare and fit to models of oriented structures.\n\nWe do run into some issues as we begin to apply orientation distributions that I will highlight with the \u2018stock\u2019 spectra prediction calculator. As we apply orientation distributions with the array utility, the results tend to depend on the initial angle one sets, even for a uniform distribution.\n\nFor example, if I apply the uniform distribution (attached as uniform.txt) to the parallelepiped model in both theta and psi directions (i.e. equivalent weighting to all out of plane and c-axis rotation angles with one in-plane direction evaluated) the results do not match our predictions for what a parallelepiped oriented at 60 deg in plane should look like (Note: length and scale parameters are just what are provided initially for the model):\n\ncorona-fig-1.png\n\nIf I change the theta and psi angles \u2013 which I would not expect would change anything because I have imported a custom distribution \u2013 I can get some drastic changes to the spectra, eventually leading to a similar spectra to what we have predicted with our own code:\n\ncorona-fig-2.png\n\nOur initial hypothesis was that changing these angles changes the initial angle the distribution is evaluated at, but this doesn\u2019t make sense for the uniform distribution we are testing here. Have we set up the array wrong? I\u2019ve also tried an array that runs from 0 to 360 degrees, but that doesn\u2019t change anything. Additionally, the results get more confusing with non-uniform distributions, and I will not go into details on those unless it can be helpful to solving this problem \u2013 I think that fixing whatever is causing this will fix those problems we are having too.\n\nLet me know if I can provide more information from what we have been seeing with the non-uniform distributions (if the solution is not obvious).",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2018-02-14T11:20:55",
    "component": "SasView",
    "summary": "Orientation distributions seem to depend on initial angle",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by smk78** [comment]
Trac update at `2018/02/14 11:21:30`: 
* **smk78** changed attachment from "" to "uniform.txt"
* **smk78** commented:

Uniform distribution

**Comment by smk78** [comment]
Trac update at `2018/02/14 11:21:56`: 
* **smk78** changed attachment from "" to "corona-fig-1.png"
* **smk78** commented:

Corona Fig1

**Comment by smk78** [comment]
Trac update at `2018/02/14 11:22:23`: 
* **smk78** changed attachment from "" to "corona-fig-2.png"
* **smk78** commented:

Corona Fig2

**Comment by smk78** [comment]
Trac update at `2018/02/14 11:23:58`: **smk78** commented:

Also see related orientation tickets:
#1111
#1121
#1124

**Comment by butlerpd** [comment]
Trac update at `2018/05/17 01:11:39`: 
* **butler** commented:

This may be a case of misunderstanding of the documentation.  Given that the major update for this release is ''fixing'' the orientational distribution this tickets needs to be resolved before releasing.  It could be an error in the code or an error in understanding.  In the latter case the documentation should be looked at since this is one of the expert groups in shear SANS and oriented SANS.  If they are confused it is not clear that any user will be able to figure it out?


* **butler** changed milestone from "SasView 4.3.0" to "SasView 4.2.0"
* **butler** changed priority from "major" to "blocker"

**Comment by butlerpd** [comment]
Trac update at `2018/07/21 19:15:31`: 
* **butler** commented:

The original worry I believe has been resolved, including fixing a problem with the builtin uniform distribution.  The group now agrees with the orientation definition and rotation matrix and they get the same results from their code for cases with no orientational distribution.  

The problem now is validating the orientational distribution which is a much harder tasks since the current typical way this is done seems to be through an order parameter defined in the plane of the detector whereas !SasView is trying to go a step (or two) further and bring real physical insights by using the real 3D object and defining an orientational distribution in the frame of the object and then projecting that onto the plane of the detector.  I am thus going to close this out and open a new ticket to validate the orientational distribution.


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "new" to "closed"
