### ISSUE TITLE
document limits on parameter ranges for Hayter-Penfold structure factor (Trac #1152)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#1193]
Setting the charge to 204 in the following parameter set breaks the Hayter_MSA model:

```text
sasview_parameter_values:scale,False,1,0,inf
:background,False,0.001,-inf,inf
:sld,False,3.5,-inf,inf
:sld_solvent,False,6.3,-inf,inf
:radius,False,300,0,inf
:volfraction,False,0.2,0,0.74
:charge,False,204,0,250
:temperature,False,293,0,450
:concentration_salt,False,0.02,0,inf
:dielectconst,False,78,-inf,inf
```

The docs don't say anything about it.

Migrated from http://trac.sasview.org/ticket/1152
```json
{
    "status": "closed",
    "changetime": "2019-03-28T09:15:45",
    "_ts": "2019-03-28 09:15:45.034571+00:00",
    "description": "Setting the charge to 204 in the following parameter set breaks the Hayter_MSA model:\n\n{{{\nsasview_parameter_values:scale,False,1,0,inf\n:background,False,0.001,-inf,inf\n:sld,False,3.5,-inf,inf\n:sld_solvent,False,6.3,-inf,inf\n:radius,False,300,0,inf\n:volfraction,False,0.2,0,0.74\n:charge,False,204,0,250\n:temperature,False,293,0,450\n:concentration_salt,False,0.02,0,inf\n:dielectconst,False,78,-inf,inf\n}}}\n\nThe docs don't say anything about it.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2018-08-03T19:33:59",
    "component": "SasView",
    "summary": "document limits on parameter ranges for Hayter-Penfold structure factor",
    "priority": "trivial",
    "keywords": "",
    "milestone": "SasView 4.3.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by pkienzle** [comment]
Trac update at `2018/08/03 19:34:30`: **pkienzle** commented:

Note that the default parameter range is limited to 200, so this isn't a problem in practice.

**Comment by RichardHeenan** [comment]
Trac update at `2018/08/06 09:17:58`: **richardh** commented:

This ticket is perhaps really part of http://trac.sasview.org/ticket/859.  

The Hayter-Penfold rmsa S(Q) has a lot of "instabilities" which may be due to the physical limitations and/or numerical approximations used in generating it. Paul Butler and Richard had some discussions by email with Paul Fitzgerald in Sydney in Feb & March 2017 regarding issues he had seen. Jeff Penfold's view is that this S(Q) should not be pushed too far. For the record, an editied version of the email string is about to be included on http://trac.sasview.org/ticket/859

**Comment by smk78** [comment]
Trac update at `2019/03/28 09:15:33`: **smk78** commented:

The model docs for hayter_msa now include a specific note about the charge limits, and I have added comments to the source code that reference this ticket and ticket http://trac.sasview.org/ticket/859. The purpose of this ticket has therefore been met and I am closing it.

**Comment by smk78** [comment]
Trac update at `2019/03/28 09:15:45`: 
* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "new" to "closed"
