### ISSUE TITLE
fix VR for core_shell_cylinder, fractal_core_shell and hollow_cylinder (Trac #1160)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#1199]
The VR function returns the volume of the whole and the volume of a part, creating the volume ratio:

```text
    ratio = part / whole
```
The volume fraction used for the structure factor is then `Vf/ratio`.

This is appropriate when Vf refers to the volume fraction of shell rather than the volume fraction of the whole particle.  Scaling by the volume ratio turns it into the volume fraction of the whole particle when calling the structure factor model.

Compared to sasview 3.x, we have the following VR functions in sasmodels:
rison with sasview 3.x

```text
    core_shell_cylinder = shell / total [ 1 in sasview 3.x ]
    core_shell_sphere = 1 [ was 1 in sasview 3.x ]
    fractal_core_shell = shell / total [ model not in sasview 3.x? ]
    hollow_cylinder = total / shell [ was shell / total in sasview 3.x ]
    hollow_rectangular_prism = shell / total  [ was 1 in sasview 3.x ]
    hollow_rectangular_prism_thin_walls = surface area / total [ was 1 in sasview 3.x ]
    vesicle = shell / total [ was shell / total in sasview 3.x ]

    * core_shell_sphere has code for shell / total, but that was replaced with 1 when we added sesans support
    * hollow_cylinder is returning total/shell rather than shell/total
    * hollow prisms had ER and VR defined as 1 in 3.x
```

We should remove VR for core_shell_sphere, core_shell_cylinder and fractal_core_shell, and fix the hollow_cylinder ratio.

See also ticket #1097.

Migrated from http://trac.sasview.org/ticket/1160
```json
{
    "status": "closed",
    "changetime": "2018-09-08T13:13:31",
    "_ts": "2018-09-08 13:13:31.227411+00:00",
    "description": "The VR function returns the volume of the whole and the volume of a part, creating the volume ratio:\n{{{\n    ratio = part / whole\n}}}\nThe volume fraction used for the structure factor is then `Vf/ratio`.\n\nThis is appropriate when Vf refers to the volume fraction of shell rather than the volume fraction of the whole particle.  Scaling by the volume ratio turns it into the volume fraction of the whole particle when calling the structure factor model.\n\nCompared to sasview 3.x, we have the following VR functions in sasmodels:\nrison with sasview 3.x\n{{{\n    core_shell_cylinder = shell / total [ 1 in sasview 3.x ]\n    core_shell_sphere = 1 [ was 1 in sasview 3.x ]\n    fractal_core_shell = shell / total [ model not in sasview 3.x? ]\n    hollow_cylinder = total / shell [ was shell / total in sasview 3.x ]\n    hollow_rectangular_prism = shell / total  [ was 1 in sasview 3.x ]\n    hollow_rectangular_prism_thin_walls = surface area / total [ was 1 in sasview 3.x ]\n    vesicle = shell / total [ was shell / total in sasview 3.x ]\n\n    * core_shell_sphere has code for shell / total, but that was replaced with 1 when we added sesans support\n    * hollow_cylinder is returning total/shell rather than shell/total\n    * hollow prisms had ER and VR defined as 1 in 3.x\n}}}\n\nWe should remove VR for core_shell_sphere, core_shell_cylinder and fractal_core_shell, and fix the hollow_cylinder ratio.\n\nSee also ticket #1030.\n",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2018-08-21T21:16:12",
    "component": "SasView",
    "summary": "fix VR for core_shell_cylinder, fractal_core_shell and hollow_cylinder",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "butler",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2018/08/23 13:01:00`: 
* **butler** commented:

aha .. yes that makes sense ... never did quite understand the point of VR.  We should check the latest documentation and update so it is clear (maybe it has been since I last looked)... and of course fix post haste.

The problem with nomenclature I guess is who we want to target.  From the lab experimentalist's point of view the "shell" volume fraction is in fact the '''actual''' volume fraction (what else is there?!!) while from the point of view of the scattering theorist the '''real''' volume fraction will be the whole object.  Actually the difference more generally is the volume fraction of the species doing the scattering (wherever inside a nominal object it is distributed) vs the effective volume fraction from the point of view of the interaction radius and of the normalization volume for the nominal object being used to create the form factor.  This is usually a shell but I guess one could imagine other cases?

Indeed this is a classic gotcha when looking at things like large vesicles (I would say newbies but plenty of none newbies have been bitten - names shall remain redacted). At just a few volume percent (non charged system) you don't have to worry about interactions... true except that since all the lipid is actually in a shell the '''real''' volume fraction is 3 to 5 times what you put in (depending on radius) and so interactions become important much sooner than expected.


* **butler** changed owner from "" to "butler"
* **butler** changed status from "new" to "assigned"

**Comment by RichardHeenan** [comment]
Trac update at `2018/09/04 13:48:48`: **richardh** commented:

As discussed at code camp: 

Note VR calculation is only used when model is multiplied by S(Q) - historically some confusion  has arisen as to when VR should be provided, which is only for hollow particles where the user knows the volume fraction of material in the shell rather than the whole particle.

product.py expects VR function to return part & whole volume in that order, thus as noted above hollow_cylinder is currently incorrect.

vesicle model uniquely has ''both'' scale and volfraction, but is using scale with VR correction if multiplied by S(Q), thus the correct behavior would only happen if volfraction is set to 1.0 when using S(Q), after discussion it was decided to edit vesicle model to conform with the other hollow particle models.

**Comment by pkienzle** [comment]
Trac update at `2018/09/06 15:15:13`: **pkienzle** commented:

See ticket #1097
