### ISSUE TITLE
5.0 issue - Allow changing parameter values on theory FitPages after first compute (Trac #1196)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1230]
While testing 5.0-beta.1 for a user question I found that I can create a new !FitPage without data, choose a model and change the parameters then hit "calculate."  This does not generate a plot but instead changes the compute button to a "show plot" button. 

My problem is that if I know want to change the value of a parameter and see how that changes things, the line goes dark blue with the new value being added but no compute button comes back and clicking on "show plot" does absolutely nothing.

This actually brings up another point.  While I like the idea of having the option sometimes of not seeing the plot, I think the default in most cases is to see it.  Certainly in the theory case, the very point of playing with parameters is to see what they do to the plot -- having to hit two buttons to get that is painful.  We may want to discuss when to hold back on the auto plotting and when not to.  However at the least one must be able to alter theory parameters and see an updated plot

Migrated from http://trac.sasview.org/ticket/1196
```json
{
    "status": "new",
    "changetime": "2018-11-21T13:32:51",
    "_ts": "2018-11-21 13:32:51.373594+00:00",
    "description": "While testing 5.0-beta.1 for a user question I found that I can create a new !FitPage without data, choose a model and change the parameters then hit \"calculate.\"  This does not generate a plot but instead changes the compute button to a \"show plot\" button. \n\nMy problem is that if I know want to change the value of a parameter and see how that changes things, the line goes dark blue with the new value being added but no compute button comes back and clicking on \"show plot\" does absolutely nothing.\n\nThis actually brings up another point.  While I like the idea of having the option sometimes of not seeing the plot, I think the default in most cases is to see it.  Certainly in the theory case, the very point of playing with parameters is to see what they do to the plot -- having to hit two buttons to get that is painful.  We may want to discuss when to hold back on the auto plotting and when not to.  However at the least one must be able to alter theory parameters and see an updated plot",
    "reporter": "butler",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Bug Fixing",
    "time": "2018-10-15T02:07:44",
    "component": "SasView",
    "summary": "5.0 issue - Allow changing parameter values on theory FitPages after first compute",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 5.0.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by RichardHeenan** [comment]
Trac update at `2018/10/22 11:32:32`: 
* **richardh** commented:

I don't see the same issue on my local build of 5.0

Having done "show plot" the first time to generate a plot (which has a blue line), the plot then updates if I change parameter values. Agreed hitting "show plot" again does nothing, unless you have closed the plot, when a new one appears.

Yes we do need to discuss whether sending data to a fit tab should produce a plot, I think yes, but Piotr disagreed, hence we have the "show plot" button in 5.0 instead of "calculate".

Should also discuss if we want an on-screen button for "new fit page" as it is only in the "fitting" drop down at the top of the screen.


* **richardh** changed summary from "Allow changing parameter values on theory FitPages after first compute" to "5.0 issue - Allow changing parameter values on theory FitPages after first compute"

**Comment by rozyczko** [comment]
Trac update at `2018/11/21 13:32:51`: **piotr** commented:

> Should also discuss if we want an on-screen button for "new fit page" as it is only in the "fitting" drop down at the top of the screen.

This does make sense. Adding a new page for theories is "conveniently" hidden under main app menus.
I added a button (+relevant tooltip) in the right upper corner of the tabbed fitting widget.
