### ISSUE TITLE
Copy over pdfs of updated correlation function tutorial before 4.2.1 release (Trac #1227)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1256]
The correlation function help file and tutorial have been updated to fix #1254.

Unfortunately, the tutorial build server is not building at the moment so there are no pdf's of the updated tutorial to distribute with the release. Hence this blocking ticket.

Wojtek is aware.

Migrated from http://trac.sasview.org/ticket/1227
```json
{
    "status": "closed",
    "changetime": "2019-02-19T05:38:13",
    "_ts": "2019-02-19 05:38:13.411299+00:00",
    "description": "The correlation function help file and tutorial have been updated to fix #1225.\n\nUnfortunately, the tutorial build server is not building at the moment so there are no pdf's of the updated tutorial to distribute with the release. Hence this blocking ticket.\n\nWojtek is aware.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Documentation",
    "time": "2019-02-15T14:00:40",
    "component": "SasView",
    "summary": "Copy over pdfs of updated correlation function tutorial before 4.2.1 release",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.2.1",
    "owner": "smk78",
    "type": "task"
}
```

**Comment by butlerpd** [comment]
Trac update at `2019/02/16 03:11:30`: **butler** commented:

Note this is '''not''' a 4.2.1 but a 4.3 release issue.  Ticket #1254 was created about a week after the final release process was started and a day after the pre-release (i.e. end of process except to check that the release builds did not introduce anything untoward) was released.  These tutorials are therefore not included in that release build.  However, the tutorials are a separate repo and I would argue can be updated on the website independently of the !SasView release cycle.  of course if that is the case it probably should go against a different milestone than the release milestones?

**Comment by smk78** [comment]
Trac update at `2019/02/16 17:47:15`: **smk78** commented:

I wasn't aware that the website change had also altered how we deploy the documentation. This ticket and #1258 were therefore trying to ensure that the bundled documentation and the web documentation were in synch as per the instructions in /tutorials/README.md If we now have full auto-deployment and these instructions are deprecated, great!

**Comment by butlerpd** [comment]
Trac update at `2019/02/19 05:38:13`: 
* **butler** commented:

not fully deprecated but lots of confusion with the changes due to the new website.  At this point however this ticket can be closed. @smk78 has updated readmes and copied files to appropriate places. Releases of Tutorials happens independently of !SasView releases which will bundle the latest tutorials at the time of the release.  Discussion about whether to keep the full pdf tutorials bundled in the release or just have !SasView point the the appropriate website page is ongoing. Either way this ticket can now be closed.


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "new" to "closed"
