### ISSUE TITLE
RELEASE.html needs updating before 4.2.1 release (Trac #1228)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1257]
http://www.sasview.org/docs/user/RELEASE.html needs updating before 4.2.1 is released.

Migrated from http://trac.sasview.org/ticket/1228
```json
{
    "status": "closed",
    "changetime": "2019-02-16T02:55:11",
    "_ts": "2019-02-16 02:55:11.468827+00:00",
    "description": "http://www.sasview.org/docs/user/RELEASE.html needs updating before 4.2.1 is released.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "wontfix",
    "workpackage": "SasView Documentation",
    "time": "2019-02-15T18:17:35",
    "component": "SasView",
    "summary": "RELEASE.html needs updating before 4.2.1 release",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.2.1",
    "owner": "",
    "type": "task"
}
```

**Comment by butlerpd** [comment]
Trac update at `2019/02/16 02:55:11`: 
* **butler** commented:

Closing this ticket as "won't fix" I guess.  This is not correct.  In principle one should '''never''' replace an individual file in the docs repo.  It is only a separate repo from github.io because the sphinx generate html documentation conflicts with the jekyll generated websites.  Technically the repo is acting as a folder under the website.

The deployment instructions have been [wiki:DevNotes/Processeses/DeploymentProcess updated on the wiki] to explain but basically, at the same time as the pre-release tag gets converted to full release the entire sphinx documentation folder from the release gets dumped in this "folder" (after the existing contents get moved to "old_docs").  Thus this step (which includes the release notes) will get copied shortly since 4.2.1 release is almost complete (except for testing that the release build is working properly as opposed to the master build)


* **butler** changed resolution from "" to "wontfix"
* **butler** changed status from "new" to "closed"
