### ISSUE TITLE
Copy updated corfunc_help to Github for new website docs (Trac #1229)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1258]
The corfunc_help.rst committed to fix #1254 needs copying to https://github.com/SasView/docs for the new online documentation (see Ricardo's email to developers of 11/02/19).

Migrated from http://trac.sasview.org/ticket/1229
```json
{
    "status": "closed",
    "changetime": "2019-02-19T05:44:22",
    "_ts": "2019-02-19 05:44:22.343188+00:00",
    "description": "The corfunc_help.rst committed to fix #1225 needs copying to https://github.com/SasView/docs for the new online documentation (see Ricardo's email to developers of 11/02/19).",
    "reporter": "smk78",
    "cc": "",
    "resolution": "invalid",
    "workpackage": "SasView Documentation",
    "time": "2019-02-15T18:25:06",
    "component": "SasView",
    "summary": "Copy updated corfunc_help to Github for new website docs",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.2.1",
    "owner": "mathieu",
    "type": "task"
}
```

**Comment by butlerpd** [comment]
Trac update at `2019/02/16 03:05:26`: **butler** commented:

As mentioned on closing ticket #1256 this is '''not''' how the docs should be handled.  I am leaving this open for now nonetheless for discussion at Tuesday's meeting.  Assuming that the doc change which was a 4.3 ticket not a 4.2.1 ticket, remains a fix to 4.3, one could cheat and replace this and the appropriate index file I guess to effectively slip in some changes under the radar.  Not sure that is a good precedent to set but.... ?

**Comment by smk78** [comment]
Trac update at `2019/02/16 17:46:26`: **smk78** commented:

I wasn't aware that the website change had also altered how we deploy the documentation. This ticket and #1256 were therefore trying to ensure that the bundled documentation and the web documentation were in synch as per the instructions in /tutorials/README.md If we now have full auto-deployment and these instructions are deprecated, great!

**Comment by butlerpd** [comment]
Trac update at `2019/02/19 05:44:22`: 
* **butler** commented:

Lots of confusion with the new website structure. The docs are a strict copy of the release docs folder.  Any file additions changes need to be made in !SasView prior to release and built by sphinx during the build process. Since the release process started on Feb 10 it has been agree that these changes will be part of 4.3 (or whatever the next release is).  Thus closing this ticket as invalid (cannot copy an rst file to the docs repo)


* **butler** changed resolution from "" to "invalid"
* **butler** changed status from "new" to "closed"
