### ISSUE TITLE
v5.0 Append functionality is too generous

### ISSUE THREAD

**Issue by mdoucet** [SasView/sasview#1327]
When wanting to overlay data to an existing plot, you can select a data set and click "Append to". What happens then is that all the data set related to the one you selected will be added to the plot. Ideally only the data would be added, with perhaps an option to add related data of the user's choice.

**Comment by rozyczko** [comment]
All checked in items in the File Explorer get added with "Append To" or displayed with "Create New".
Switching off the main data does not untick related models under it currently.
I am not sure it should but we might implement a tri-state on the data items. Single click would deselect just the data and another click would also deselect all dependent datasets (model, residual etc).
This is a pretty standard UI behaviour so probably would be better than a simple on/off for all children items.

**Comment by smk78** [comment]
Hmm. I see this issue currently has an 'enhancement' label. I think it is actually a bug (sorry!). It is really irritating. It means Append to Graph is virtually useless in 5.x. We don't have this issue in 4.x.

Just so we are clear what the issue is:
Load a data set. Send it for Fitting/Inversion/etc. Do a fit/etc so you get some graph windows. Untick the current data. Now load another dataset and try appending it to an existing graph window. You can end up with I(q), Mn, Residuals, P(r), etc all plotted on the same graph!

**Comment by rozyczko** [comment]
The point is - we want a way to enable plotting data from different datasets on one chart.
E.g. comparing two datasets or two models for two separate datasets. This means we need to be able to select (any) items in the data explorer and have them plotted. Append is just doing that - appending everything that is selected. The very same thing happens in 4.x, EXCEPT the dependent plots (model, residuals etc) are not selected by default.
In 4.x if I select these and click Append - I get the same behaviour as in 5.0
It looks like the first/easiest fix is to deselect dependent plots on creation. This will help avoid confusion and mimic 4.x
The next step would be to consider the tristate checkbox for the main dataset as mentioned above.

**Comment by rozyczko** [comment]
set the initial status of those checkboxes to Unchecked, as they were in 4.x

**Comment by rozyczko** [comment]
Please review if the above solution and future work is as expected.

**Comment by mdoucet** [comment]
That works fine.
