### ISSUE TITLE
5.0 check custom pinhole smearing.

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#1358]
Comparing the code in wx GUI

  https://github.com/SasView/sasview/blob/ad52f1af2f5f6fd51960f7e8feafc299e9bb91e7/src/sas/sasgui/perspectives/fitting/fitpage.py#L2368

to the code in the Qt GUI

  https://github.com/SasView/sasview/blob/11296b90562035e7c7ae550953f64170e0caeb57/src/sas/qtgui/Perspectives/Fitting/SmearingWidget.py#L340

and ticket-1094-headless

  https://github.com/SasView/sasview/blob/f5f71e42a491e7dcca1039cc2586e2ec27a54d22/src/sas/sascalc/fit/fitstate.py#L319

Note that the first assigns to dqx_data while the other two assign to dx_data.

**Comment by butlerpd** [comment]
Ooops - my bad. That was fixed in comit https://github.com/SasView/sasview/commit/462e019c03ac63171066f5530e8a86a4e2e17034 which I forgot (didn't think?) to propagate to ESS_GUI ... and did not realize headless was yet a separate master branch?

The line is setting pinhole resolution for 2D in which dqx and dqy are the same (as opposed to slit smeared where they would be different). There had clearly been a longstanding typo!!  Not sure to what extent, if any, it affects the computation other than for 2D theories which get their dq from the GUI.

This should be fixed in ESS_GUI.  Not sure the meaning of it in headless?

**Comment by rozyczko** [comment]
The fix has been merged into ESS_GUI at some point. Closing.
