### ISSUE TITLE
Windows installer shortcut is misnamed

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1412]
Testing 5.0.1 release candidate on x64 under W10.
The desktop shortcut created is named sasview-5.0 and thus overwrote the existing shortcut for the 5.0.0 release version!

**Comment by rozyczko** [comment]
Isn't that what's supposed to happen? 5.0.1 is a patch with bug fixes, so we do want to replace existing installation/shortcuts rather than create new. This is still SasView 5.0.
Now, as I think of it, we should give users a chance to uninstall the existing, previous version of 5.x before continuing. They might want to and this should possibly be the default, but at least it would allow having more than one dot release at the same time.

**Comment by smk78** [comment]
I think what we have just identified is a difference in outlook between a software purist and a pragmatic scientist!

I have every version of SasView currently installed so that when I find something unexpected I can compare/contrast behaviour. We usually also have the current & last versions installed on the instrument analysis computers. Same thing with Mantid.

So yes, I wouldn't advocate overwriting by default, let the user choose at installation. Mantid, for example, always offers up C:\MantidInstall as the installation folder. If you want to overwrite, fine. If not you just tack, say, -x.x.x to the end before you click OK.

**Comment by rozyczko** [comment]
5.0 ready for testing on Win64

**Comment by rozyczko** [comment]
Ready for testing on Win64

**Comment by smk78** [comment]
Latest versions of the installer let you choose the installation path. That's fine. So I think this issue can now be closed.
