### ISSUE TITLE
Sort out the Invariant Perspective & Documentation (#1434 & #1461)

### ISSUE THREAD

**Issue by wpotrzebowski** [SasView/sasview#1472]
Sort out the Invariant Perspective & Documentation (#1434 & #1461)

**Comment by smk78** [comment]
Ahead of the 5.0.2 release, invariant_help.rst from the ticket-1434 branch (the most current invariant docs) has been cherry-picked and copied into ESS_GUI master.

I have then added in the pre-prepared 5x invariant panel screenshots which also necessitated a small change the 'Using Invariant Analysis' text due to different behaviour to 4x

**Comment by butlerpd** [comment]
Now that the first pass fix is understood and tested for 4.x need to make those changes to the 5.x branch.

**Comment by butlerpd** [comment]
This was created for the hackathon.  Only #1461 was relevant to 5.x the remaining #1434  needs to be finished but is an issue in 4.x so am going to close this issue
