### ISSUE TITLE
Problem using constraints in 5.x

### ISSUE THREAD

**Issue by wpotrzebowski** [SasView/sasview#1490]
Reported by a user: 

"When you add constraints, it is a pain and it is not working.
you can not define all M1= M2 and M3=M2  (with M1, M2 and M3 having 10 parameters)
also you can not remove more than one constraint

there are some bugs in this part.
The old version was easier to handle.
I had 3 curves and it only displays M3 twice and M1 if I want to add constraints. M2 does not exist for some reasons.

Also how can you add constraint by yourself?
once you filled the lines, you have to pass by the add constraint bottom to add constraints and not being able to type them… or copy paste..."

**Comment by butlerpd** [comment]
As per today's conversation am moving this to a 5.0.3 milestone in preparation for a 5.0.2 release.

**Comment by butlerpd** [comment]
As per today's conversation am moving this to a 5.0.3 milestone in preparation for a 5.0.2 release.

**Comment by gonzalezma** [comment]
Tests using a standard case and comparing 5.0.1 with the new ESS_GUI_1490 branch:
[SasView5_constraints_UI.pdf](https://github.com/SasView/sasview/files/4540058/SasView5_constraints_UI.pdf)

**Comment by gonzalezma** [comment]
Updated ESS_GUI_1490 branch works reasonably well:
[SasView5_constraints_UI_2.pdf](https://github.com/SasView/sasview/files/4540070/SasView5_constraints_UI_2.pdf)

**Comment by RichardHeenan** [comment]
My views re questions asked in the pdf above.
Q1.  all or only adjustable params on the left side ? Difficult one this as lots of users will start by wanting to constrain all in one FitPage to all in another, then edit some of the constraints.  If you later "fix" the parameter, the constraint on it may  still exist in the maths but is not actually being used (thus ought to change back to the normal font). Of course being able to save and reload projects with multiple data and multiple constraints is good.
What we now still need is a way to switch data set associated with a FitPage. Having set up my complex constraints across several data sets I have to enter all the constraints over again for different data. i.e. send data to overwrite that for any current FitPage. Yes there is a copy fitPage, but it won't replicate the constraints.]
Q2 - OK
Q3 as per Q1, I think need to add everything, but you might convince me otherwise.
Q4.1 & 4.2, agree
Q5 I need to try 5.0.2
Q6 yes a mechanism to delete a constraint would be useful
Q7 yes we ought to check for bad syntax, non-existent parameters before accepting the constraint

**Comment by wpotrzebowski** [comment]
Closing this issue as PR #1533 has been merged
