### ISSUE TITLE
Plot legend visibility toggle needs to be restored

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1523]
@smk78 Notes that: Modify Plot Property functionality that allows the user to change, for example, axis labels, needs to be brought back into 5x. This related to but different from issue #1414 in that both were plotting functionality that were lost in the move from 4 to 5 and need to be at least restored (though they could also use improvement). 

NOTE: the DREAM plots do contain the toolbar with all manner of plot control options.  I guess these are being served by bumps directly instead of SasView?.

**Comment by rozyczko** [comment]
I have it on my list and am currently testing but this won't be merged into 5.0.2. Let's have it in 5.0.3/5.1 as it is "new" (in ver 5)

**Comment by rozyczko** [comment]
Re: DREAM - yes, these charts are served directly by BUMPS.

**Comment by smk78** [comment]
4.x also had the ability to toggle the legend off/on. This also needs implementing in 5.x.

And there have been complaints from users that the font size used in the legend is quite large, meaning the legend can take up a lot of real estate if the dataset names are long, and/or if plotting several datasets/theories. Would it be possible to provide some control over this?

**Comment by rozyczko** [comment]
Legend size on OSX is a separate, large issue. Not sure if this has been addressed?

**Comment by smk78** [comment]
Ahh, yes: https://github.com/SasView/sasview/issues/1337

**Comment by rozyczko** [comment]
Original request in this issue has been addressed by adding the MPL toolbar toggle.
This means the only thing to do here is to toggle legend on/off.
I will rename the issue and address the problem

**Comment by rozyczko** [comment]
Added `toggle legend` context menu item for 1D plots (quick and standard).

**Comment by sl-saxs** [comment]
I've just tried running SasView, downloaded from the ESS_GUI branch. 
The context menu (right-click into the plot window) now shows the options "Toggle Navigation Menu" and "Toggle Legend". 
"Toggle Navigation Menu"  gives the MPL toolbar. Zoom, Pan, Home, Back and Forward do work fine. However, choosing "Edit axis, curves and image parameters" from the MPL toolbar opens a window with two tabs "Axes" and "Curves" where one can edit the plot style, legend, etc. So what I did is:
1) Changed the legend the label from "M1 [flexible_cylinder]" to "mm". This changes don't appear in the legend and they don't appear in the context menu "M1 [flexible_cylinder]"  -> "Modify Plot Properties"
2) Changed the plot style from "Solid line" to "Octagon" -> these changes don't appear in the context menu "M1 [flexible_cylinder]"  -> "Modify Plot Properties" where it still says that the curve is plotted as a solid line whereas in the plot window the curve now appears as "Octagon". 
3) Changed plot style in context menu "M1 [flexible_cylinder]"  -> "Modify Plot Properties" to be "Red" and "Circles". The curve is now displayed as red circles. But choosing "Edit axis, curves and image parameters" from the MPL toolbar now opens a window with only one tab "Axes" where before it showed two tabs "Axes" and "Curves". It was the "Curves" tab where one could modify the plot style and the legend. But the comboBox in the "Curves" tab only showed one curve to be edited, in that case  "M1 [flexible_cylinder]". But more curves were shown in the plot window.
4) If one goes from the context menu "M1 [flexible_cylinder]"  -> "Modify Plot Properties" and deletes the "Legend label" completely, the legend remains unchanged in the plot window. If the "Legend label" is just modified instead of deleted completely, the modifications appear on the plot window.  
5) from the context menu -> "Toggle Legend". Makes the legend disappear if it is visible and makes it appear if it is invisible. If the legend is invisible and another curve is added to the plot or if parameters of the currently plotted curves are changed, the legend pops up again. It seems that the legend visibility doesn't persist.
