### ISSUE TITLE
NXcanSAS definition changes

### ISSUE THREAD

**Issue by krzywon** [SasView/sasview#1527]
A small change to the NXcanSAS definition is coming so the SasView reader and writer should be updated to accommodate this change.

https://github.com/nexusformat/definitions/issues/765

**Comment by prjemian** [comment]
Current version of NXcanSAS is 1.0.  Next version will be 1.1.

**Comment by smk78** [comment]
@krzywon , I was just using the 5x ticket1527 branch is create a couple of v1.1 NXcanSAS files to give the Mantid guys and noticed something. If I load a 1D CanSAS1D file it gets loaded into the Data Explorer _twice_ but only one instance is plottable. Not sure how I missed this yesterday in review, maybe because I was using the File Converter to generate the .h5.

Will now see if its the same in the 4x branch...

**Comment by smk78** [comment]
Yup. Affects 4x too.

**Comment by krzywon** [comment]
@smk78 I'll look into this today. Thanks for catching the issue.
