### ISSUE TITLE
ESS GUI Corfunc: Dataset name not appearing in Corfunc Perspective in 5.0.2

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1528]
This issue is carried over from https://github.com/SasView/sasview/issues/1339.

Unlike the other perspective windows, the corfunc window in 5.0.2 is not currently displaying the name of the dataset being analysed.

**Comment by butlerpd** [comment]
Sorry @smk78. I did see this before your mention of it but not before I had added it 😞   Looking at the state of this ticket (no further comments) and the fact that the new one gives a bit more information (i.e. it DOES work .. just requires two goes and has been verified on both mac and PC) am going to close this one as a duplicate rather than copy that info over here and then closing the other.
