### ISSUE TITLE
v5 constrained value within single FitPage not being returned to gui

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#1600]
e.g. set up a core_shell_sphere fit, set up say  thickness=radius*0.2

( select one param, ctrl/click the other, then right/c;lick )

the fits and value of radius change appropriately, so the constraint is working, BUT the value of thickness displayed in the gui is not changing to the new value.

**Comment by RichardHeenan** [comment]
Would be nice also if having got the box up to enter the constraint we could do e.g.
sld_shell= 0.7*sld_core+0.3*sld_solvent
but this seems not allowed here, though works in normal constraints between fitpages.

**Comment by pkienzle** [comment]
I do not see the update issue using PR #1628. That is, after a single page fit to a cylinder with `length = radius`, the `length` and `radius` values shown in the GUI are the same.

**Comment by RichardHeenan** [comment]
OK, I just checked again (still in PR #1628), if the constrained parameter is set to be "fitting" then it does update.

If I set up thickness=radius*0.25, then turn thickness off,  
then with radius "on" I get a good fit but the thickness value is _not_ updated.

This is dangerous as the fit is not actually for the param values displayed on the screen.

Turn thickness "on", hit fit, chi^2 stays same and the thickness is updated.

**Comment by m2cci-NMZ** [comment]
> OK, I just checked again (still in PR #1628), if the constrained parameter is set to be "fitting" then it does update.
> 
> If I set up thickness=radius*0.25, then turn thickness off,
> then with radius "on" I get a good fit but the thickness value is _not_ updated.
> 
> This is dangerous as the fit is not actually for the param values displayed on the screen.
> 
> Turn thickness "on", hit fit, chi^2 stays same and the thickness is updated.

Constraints are always applied, regardless of the parameter being selected for fitting. Since only fitted parameter values are updated in the GUI, this is causing inconsitencies. We could make the checkbox uneditable when the constraint is entered to keep it checked or not apply the constraint if the parameter is unchecked. I guess the first option would be the least confusing.

**Comment by pkienzle** [comment]
Another idea: once parameters are tied then any change to any part of one updates all the others.  So if a parameter is selected for fitting on base model, then the it will be selected for fitting on the constrained model. If it is changed to fixed on the constrained model then it will be changed to fixed on the base model. Similarly for the parameter value, ranges and output uncertainty.

Currently italics are used on the constrained parameter to indicate that it is constrained. You may want to do the same as the base parameter since they are conceptually the same underlying parameter.

When using a constraint expression rather than a tied parameter this won't work. Instead disable editing on the fitted checkbox, the value and the range.\* The independent parameters in the expression could be shown in italics to indicate that changing the value will affect the values of other parameters.


\* ...for now. Users want inequality constraints, possibly with constraint expressions on the inequality, but that is another ticket. Also, uncertainty estimates can be derived for the expression but that is another ticket.

**Comment by RichardHeenan** [comment]
> OK, I just checked again (still in PR #1628), if the constrained parameter is set to be "fitting" then it does update.
> If I set up thickness=radius*0.25, then turn thickness off,
> then with radius "on" I get a good fit but the thickness value is not updated.
> This is dangerous as the fit is not actually for the param values displayed on the screen.
> Turn thickness "on", hit fit, chi^2 stays same and the thickness is updated.
> 
> Constraints are always applied, regardless of the parameter being selected for fitting. Since only fitted parameter values are updated in the GUI, this is causing inconsitencies. We could make the checkbox uneditable when the constraint is entered to keep it checked or not apply the constraint if the parameter is unchecked. I guess the first option would be the least confusing.

If we really do need to have the box checked to be able to set up a constraint, then making the checked box uneditable, along with the change to italics, on successfully setting up a constraint seems a good idea.
