### ISSUE TITLE
Problem loading canSAS data into Invariant

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1605]
The `latex_smeared.xml` data set in the test folder includes 2 separate curves: a slit smeared low Q USANS data set and a high Q pinhole smeared SANS data set.  These are loaded as two separate files into the data manager. Checking only one of the data sets allows only that data to be sent to be plotted or to fitting and once fitted and plotted with the fit only that data set is shown.  however, when sent to the invariant both the checked AND unchecked data sets are plotted in the invariant plot though it appears the Invariant is only calculated from the chosen data set? At least the default qmin and qmax come from that data set and the extrapolations appear to be made from that data set.
NOTE:  This is true in 5.0.2 and in the local build of the 5.x invariant branch.  The dataloader work may or may not have changed this behaviour

**Comment by krzywon** [comment]
When Invariant wants to generate a new plot, it finds all data by filename, so both latex_smeared data sets are grabbed. I'm pretty sure this will be mostly resolved with #1652, because data are now labelled differently, but this won't be 100% foolproof. Ideally, the perspective would find data by data.id, which is a unique value, not by name or filename, which can have duplicate values.
