### ISSUE TITLE
Uncertainty on the Volume Fraction in the 4.x Invariant Perspective is different to that in 5.x

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1613]
With the same parameters in the Invariant Perspective, and the same data loaded, and without any extrapolations (so the simplest default calculation), the Invariant Perspectives in 4.x and 5.x return:

4.x   Volume Fraction 0.0424 +/- 2.52e-06

5.x   Volume Fraction 0.0424 +/- 0.000537 (this looks the more believable?)

Note that both perspectives return _identical_ values for the Invariant Total and its uncertainty.

**Comment by butlerpd** [comment]
@smk78, If by 4.x you mean 4.2.2 that would be EXACTLY correct :-)  as shown in the commits to the PR #1461 that was some of the major lifting done in the PR -- As I recall, the comment on one of the commits may have use the words "totally bogus" 😃 if that is the case we can close this as being the point of the PR -- error was not being reasonably calculated in 4.2.2.

If on the other hand this is comparing to PR#1461 itself we need to check the PR#1590 since the new calculation code was taken directly from PR#1461.

**Comment by smk78** [comment]
Ok, I just checked again. I think I must have been building _master_. If I build the 1434 branch this PR will merge the volume fraction and its uncertainty are the same as in the ESS_GUI 1574 branch that the PR 1590 will merge. My apologies. Am closing this ticket.
