### ISSUE TITLE
Pyinstaller doesn't add *.py files to doc/html/_downloads

### ISSUE THREAD

**Issue by wpotrzebowski** [SasView/sasview#1664]
*.py files are missing in installers documentation (e.g. barbell model) because they are not added to _downloads  by pyinstaller. They are available at earlier build stage. For online docs this was fixed in https://github.com/SasView/sasmodels/pull/421.

**Comment by butlerpd** [comment]
can we close this @wpotrzebowski? the links seem to work for me on windows 10 using installer version of 5.0.5 RC2

**Comment by butlerpd** [comment]
Since the way we get the online docs is for us to manually copy the docs directory of the installer installed SasView (see https://github.com/SasView/sasview/wiki/DevNotes_Processeses_DeploymentProcess#update-posted-documentation), the result should be identical.  It would be nice to have that automated as well at some point.   Thus I think this has been fixed in 5.0.5 so moving it back.
