### ISSUE TITLE
sasview 5,   Q resolution smearing issues with broad_peak model 

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#1711]
User Dave Barlow reports issues with the attached data set and broad_peak model.
Turning on "Use dQ data" resolution smearing _immediately fills the I(Q) array with nan, and the fit line disappears from any plots_ but does not give the user any warning. I say "turning on" here but sasview of course has the smearing on by default, hence we have confused users!

Trying a fit does give a "fit not converged" message. 
The Q resolution varies from 175% to 4.6%, I cropped out the first part of the data so it was only 43% to 4.6% but that still has the same problem.
I tried "Custom Pinhole Smear", this seem OK up to dQ/Q of ~39%, above which nan appears, hence the 43% case above fails.

Trying a couple of other models, such as cylinder, all is OK.

This is a fairly numerically unstable model, but that should really not affect the smearing, unless we are calling the model with negative or some other invalid Q ??
If it is a numerical issue, can it be flagged to the user?

[smearing_issue1.json.txt](https://github.com/SasView/sasview/files/5617383/smearing_issue1.json.txt)

**Comment by RichardHeenan** [comment]
So broad_peak is a pure python model, has minimal numerical error checking, and specifically seems to ignore any divide by zero error!  Could a python expert suggest some improvements here please:

    z = abs(q - peak_pos) * lorentz_length
    with errstate(divide='ignore'):
        inten = (porod_scale / q ** porod_exp
                 + lorentz_scale / (1 + z ** lorentz_exp))
    return inten

**Comment by pkienzle** [comment]
This is a sasmodels issue.

Large divergence will lead to negative q, but [broad peak](https://github.com/SasView/sasmodels/blob/c83e9a247a3b8c9b6ca2af70c6d4d11d5d2dd1cf/sasmodels/models/broad_peak.py#L90-L93) doesn't protect against this. Assuming circular symmetry, then `I(q) = I(-q)` so change `q ** porod_exp` to `abs(q) ** porod_exp`. 

There is an [exclusion around `q = 0`](https://github.com/SasView/sasmodels/blob/c83e9a247a3b8c9b6ca2af70c6d4d11d5d2dd1cf/sasmodels/resolution.py#L145), so even though broad peak diverges it should not cause a problem.

**Comment by pkienzle** [comment]
A better fix would be to set `q` to be positive rather than negative,  [as is done for slit resolution](https://github.com/SasView/sasmodels/blob/c83e9a247a3b8c9b6ca2af70c6d4d11d5d2dd1cf/sasmodels/resolution.py#L150).

The following models give different results for `I(q)` and `I(-q)`:

* broad_peak
* correlation_length
* flexible_cylinder
* flexible_cylinder_elliptical
* fractal
* fractal_core_shell
* guinier_porod
* hayter_msa
* line
* mass_fractal
* peak_lorentz
* pearl_necklace
* polymer_excl_volume
* spinodal
* two_lorentzian
* two_power_law

**Comment by pkienzle** [comment]
Looking at the code again, the exclusion around `q=0` is in the slit geometry only, not in the pinhole geometry. It should be added to pinhole geometry along with the sign correction.

The exclusion around `q=0` makes sense with pinhole geometry since there is a beam stop.

Is there also a beam stop for slit geometry? Or did we just add this as a hack so that divergent models don't blow up when the resolution is too broad?

**Comment by pkienzle** [comment]
Note: the matrix method uses every calculated q value when computing the resolution at each measured q point so if there are any NaN values in I(q_calc) then every smeared value will be NaN. I'm not sure if this is a bug or a feature.

**Comment by RichardHeenan** [comment]
Could there be a second version of q_calc with the absolute values of Q, that is then passed to the model, so the model only see positive Q ?

**Comment by pkienzle** [comment]
Just need to copy the slit resolution logic into the pinhole resolution code. That is, drop qcalc near zero and return the absolute value.

**Comment by butlerpd** [comment]
This seems reminiscent of a lengthy resolution discussion several years ago? Was anything pertinent to this that was discovered during that effort?  Maybe @krzywon with his magical search ability 😄 can point us to the relevant issue?

**Comment by RichardHeenan** [comment]
> 
> 
> Just need to copy the slit resolution logic into the pinhole resolution code. That is, drop qcalc near zero and return the absolute value.
It's not obvious to me where to do that, the slit resolution seems to always get Q from a sqare root, so is positive, the pinhole routine has a comment that qcalc has to be increasing.

**Comment by krzywon** [comment]
@butlerpd are you talking about #941? Otherwise, there are quite a few discussions on resolution, including #1236, #1249, and #1268, to name a few.
