### ISSUE TITLE
Too frequent fit update on parameter changes

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1767]
In many of the perspectives, editing of parameters triggers a recalculation. The problem is that in many cases this appears to happen for every key stroke.  This is particularly painful for example in the Fitting perspective with a complex model (computationally).  Changing the Q range triggers a recomputation of the model on every backspace or number typed (unless one types fast enough that some recalculations get skipped).

In most cases the computation should wait for either an apply or calculate button to be clicked or, at the very least wait for a return to signal the need for a recalc.  As it is changing the Q range for a fit can be unusable in some cases.

**Comment by rozyczko** [comment]
Hmm are you sure the recalculation happens after each keystroke and not on leaving the edit field?
I can reproduce the recalculation request on hitting TAB, Enter or clicking outside the control but not on a simple keystroke.
Can you specify in which other fields (apart of Q min, Qmax) do you see this behaviour?

**Comment by rozyczko** [comment]
Ah, this does happen but only in Jeff's Q range bars branch

**Comment by butlerpd** [comment]
Ooops! Sorry @rozyczko and great sleuthing to figure it out anyway!. I was pulling different branches and testing and failed to note which one I was testing to get this (not sure I realized - my bad)

**Comment by butlerpd** [comment]
Also Re @rozyczko previous question, one other place I know for sure I see this behavior (and I don't think it is restricted to just the slider branch) is when editing the Dmax in the P(r) perspective but there it is launching the background calculations which would be ok except that it throws errors onto the console until the final (reasonable) Dmax is entered.  Will look for other places and document here if/when I find them.

**Comment by rozyczko** [comment]
I'm confused by this change, to be honest.
The original complaint was about model updates on each keystroke, and this was already fixed by you in 5.0.3.
Subsequent issue described by Paul had to do only with the Dmax line edit in P(r).

The current behaviour of the model being recalculated at each parameter change automatically has been with 5.0 since the beginning and I believe was widely accepted as it gives an easy way to see the effect of parameter modification on results.
Why would we want to change how this works all of a sudden? Are there any complaints about the current behaviour?

**Comment by krzywon** [comment]
My PR was meant to draw out some discussion, honestly. The computation behavior of the fitting perspective is different between 4.2.2 and 5.0. In 4.2.2, the model is **not** recalculated after every parameter change, only when the compute or fit button is pressed. #1798 sets the behavior of 5.0.x to match that of 4.2.2.

In my opinion, recalculating after every parameter change is too time consuming, especially when changing multiple parameters, but adding another button to an already complex window is just more clutter. I don't think either is best but can't think of a perfect middle-ground.

**Comment by rozyczko** [comment]
Ah, I see. Yes, it will be great to have a discussion about this, since neither allowing immediate update nor having yet another button seems to be the best solution. Maybe we could bring this up on Tuesday and maybe even *gasp* ask users?

I think an even more important design issue is the ability to "reset" the parameters to the results of the last fit (or to the initial model values). This of course leads to the need for undo/redo for parameter table, which should be reasonably doable with the current way the model is being stored.

**Comment by butlerpd** [comment]
Certainly will add this to the agenda.  Actually the button should not be technically needed but historically it seems to be? Maybe because users got confused but maybe because of underlying code instabilities?

To respond to @rozyczko original comment, actually this was one of the things I thought I saw when first creating this github issue, but at the time there were soooo many of these problems I was getting confused and the focus of the testing at the time was around the new sliders.... and I was running out of time.  However, this came back as a (very polite 😃  complaint from usage at the summer school. which prompted some more testing by myself and @krzywon to verify.

To provide a historical perspective for the discussion:

The "feature" of updating as soon as a parameter is entered (signaled by moving the cursor to a different area) was the first "guess" in SasView "0" (actually SansView at the time I guess) and somehow got reverted when the GUI was changed to 5.0.  It works great as long as one sticks to simplish models. However, as users started using increasingly complex calculations and then would want to tweak several parameters at once (clearly it needs to be a longer and it looks like the radius should be shorter ...and too many oscillations so I should increase the polydisperstiy etc), the user would get frustrated having to wait, sometimes many seconds depending on model and compute power, after every parameter entry for a pointless calculation they really didn't want to see before being able to adjust the next parameter and then the next.  Eventually it became too much of a problem.

The fix was to only update if the user hit enter after entering the parameter. If they just moved the cursor to another box no update occurred. This seemed like a natural since hitting enter after typing in the number is a rather natural thing to do. The thought being if you were careful not to use that instinct then you could enter the other parameters immediately without a recalculation. Of course you then would need to have to hit enter after the last change.

I cannot recall exactly now why the compute button was necessary. I think it was partly because some users got confused about how to force an update without a fit and/or partly because, as I recall, there were problems with the code reliably updating when hitting enter so that a separate button tied directly to the calculate method was needed? Whatever the case it was introduced for some reason.  As I said above, whether that reason is still valid today is not clear (partly because my memory is not so good ☹️.

**Comment by rozyczko** [comment]
Thanks, @butlerpd. This provides some context for the current effort.
I would definitely argue that hitting `Enter` to get the model recalculated is too obscure to rely on.
If one enters a value in a field, the expected behaviour is to either have it accepted immediately or after clicking on an explicit button. Pressing a (random) key seems like a rather unfriendly design.

My reasoning for the original design was that responsive UI is something that users find more intuitive - the fewer click to get what they want, the better. I haven't had bad experience with waiting for model recalculation long enough to notice UI sluggishness but of course I was using simple models/small datasets for testing.

Giving users a choice between model update on edit vs. on button click through a general option is probably also not a good idea - interaction with the GUI should be consistent throughout the application.

Adding the "Calculate" button would however require more than a simple fix in FittingWidget. All options, checkboxes etc. are updating the state immediately so this seems like a larger redesign.

**Comment by butlerpd** [comment]
the #1798 PR is waiting for review and will hopefully @butlerpd will do that soon as promised, but just thought I'd add that during the training workshop, while helping @yunliu01 debug his model code he asked how to enter several parameter **before** sasview recalculates - sadly had to admit I had not yet reviewed the PR.  But is another example of how frustrating it can get.

**Comment by butlerpd** [comment]
This was fixed sometime ago by @krzywon and tested and seems to be working as expected in 5.0.5 rc1. Am therefore closing this ticket as resolved
