### ISSUE TITLE
v5 zero value for dx causes resolution smearing to not happen

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#1804]
Having just had a data set where one single dX value was zero, and then spent ages trying to work out why I could not ask for Q resolution smearing (which I would have expected to be on by default), could the loader please flag this as an issue.

This may perhaps be the reason behind some other mysterious complaints ?

**Comment by butlerpd** [comment]
I too have seen a few times where things would behave very badly where it turned out to be the last data point having a zero (or possibly missing?) value for dI or maybe sigma Q (I cannot remember). Removing that line allowed things to work.  Should we be adding a validity check on column 3 and 4 (should they exist)? is a zero the only bad value? is zero guaranteed to be wrong? I think we already have some validation checks?

**Comment by krzywon** [comment]
In the [wxPython branch](https://github.com/SasView/sasview/blob/9c9853b389c2e01dc40cdce6e0729846f3921112/src/sas/sascalc/fit/qsmearing.py#L84), pinhole smearing is set when `len(data.dx) == len(data.x)` which is another, possibly better, option.

One other key difference between 4.x and 5.x is the [check for SESANS](https://github.com/SasView/sasview/blob/master/src/sas/sascalc/fit/qsmearing.py#L55). I don't see any checks for SESANS in the 5.x SmearingWidget. Maybe this is happening elsewhere, but struck me as a potential issue.

**Comment by dehoni** [comment]
I've tested the SESANS with some mock-up of the test data sphere2micron.ses. For 5.x the odd dx=0 value is catched and silently   "use dQ data" is no option for instrumental smearing. I do not know where this happens. For 4.x, dx=0 produces an error "'one or more of your dx values are negative, please check the data file!". That is the expected behaviour looking at the test in [Qsmearing.py](https://github.com/SasView/sasview/blob/9c9853b389c2e01dc40cdce6e0729846f3921112/src/sas/sascalc/fit/qsmearing.py#L66).
