### ISSUE TITLE
Update "Getting started tutorial" to refer to 5.0.4

### ISSUE THREAD

**Issue by wpotrzebowski** [SasView/sasview#1863]
Current version of tutorial says 5.0.0. New screenshot has to be created

**Comment by smk78** [comment]
We should be careful we don't make a rod for our backs here (ie, by implicitly undertaking to update the tutorial for every release).

To be fair, a paragraph present in the 3.x/4.x 'Getting Started' tutorial seems not to be present in the 5.x version:
```
If you want to install an earlier release of SasView, click on ‘links/downloads’ in the menu
bar and then, under ‘Release versions’, click on the link ‘All versions from 3.0’.
```
Then the fact the screenshot is out of date is less important.

However, if someone is updating the 5.x tutorial, then there are some other tweaks needed:
- Year references to 2019 should become 2021 throughout
- The Supported Platforms section needs some tlc in light of what we now know about dependencies

**Comment by butlerpd** [comment]
I was also going to suggest that we don't have enough people to write tutorials in the first place (with only 25% of the currently envisaged tutorials completed) so that having to go through each tutorial as part of each release to update any image showing the wrong version number would be prohibitive now and become more so as we add more tutorials.

I suggest we try to
1. Minimize graphics that show version numbers or dates
2. Regardless, only update a tutorial when the functionality or interface discussed in the tutorial has changed

That's my 2 cents worth anyway as the saying goes 😃

**Comment by butlerpd** [comment]
@smk78 and @wpotrzebowski should we close this as "won't fix" or change the ticket to something sustainable? Maybe a discussion ticket about how to handle keeping tutorials up to date and what that means?

**Comment by smk78** [comment]
Let me have a look. Won't be immediately though!

**Comment by smk78** [comment]
@wpotrzebowski / @butlerpd: I have just pushed some updates to the Getting Started tutorial for v5 in \tutorials. The new document can be viewed here: [getting_started_with_sasview_v5.pdf](https://github.com/SasView/sasview/files/8063694/getting_started_with_sasview_v5.pdf)

Before this is added to the release branch or the website, do you see a need for any further changes? In particular, in the 'Support Platforms' section?

**Comment by butlerpd** [comment]
Hummm.... I was thinking we were going for limiting the need to remember to update all the tutorials for every point release but I see there is an issue due to the Mac OS platforms? .. but it looks like that is not an issue with the other tutorials? 

Otherwise looks fine to me - but I cannot speak to the Mac OS or Linux platform support.

**Comment by smk78** [comment]
I suppose I could shunt the platforms bit to the FAQ and in the tutorial just direct the reader to that?

**Comment by butlerpd** [comment]
Hadn't thought of that. That might work. The fact that mac is so sensitive to be the latest OS is really annoying. Another alternative might be to change the last entry to say 5.0.5 and above? At least then it only needs changing when the OS requirement changes... on the other hand we could forget? Am starting to think your first solution might be better...

**Comment by wpotrzebowski** [comment]
I think it makes sense to move platforms to FAQ and update if needed.

**Comment by smk78** [comment]
@butlerpd / @wpotrzebowski : How's this?
https://www.sasview.org/faq/#what-platforms-does-sasview-run-on

[getting_started_with_sasview_v5_new.pdf](https://github.com/SasView/sasview/files/8074089/getting_started_with_sasview_v5_new.pdf)

**Comment by butlerpd** [comment]
Nice!! Elegant solution I think?

**Comment by wpotrzebowski** [comment]
Nice! Maybe I would only reverse order. I guess people maybe interested mostly in latest version(s)?

**Comment by smk78** [comment]
Ok. Order reversed!

**Comment by smk78** [comment]
Replaced 'getting started' tutorial pdf in release_5.0.5 branch with updated version. https://github.com/SasView/sasview/commit/2b894cbdbc9c5526887bc8d337d88219936537aa
