### ISSUE TITLE
New version string confuses StrictVersion check

### ISSUE THREAD

**Issue by rozyczko** [SasView/sasview#1872]
StrictVersion() call on the new format version string `5.0.5-alpha.1` seems to confuse distutils.version.StrictVersion() check with default versioning of distutils (3.6.13)

Attempting to start SasView on either Linux or Windows fails with
```
ValueError: invalid version number '5.0.5-alpha.1'
```

**Comment by butlerpd** [comment]
Interesting --- I had forgotten we do use the version number for one thing besides printing the string in various places: "checking whether I am the latest version."  I guess that is where we are using StrictVersion rather than LooseVersion?

As I understand it, PEP 440 covers StrictVersion? If so I note that besides a, b and rc (instead of alpha, beta etc,) a dev and post tags are also allowed?  Given the rationale for adding the tag after a release, the dev tag may be more appropriate than a(lpha). From what I can tell we should avoid using the post tag.  So, my suggestions is that we replace the original suggestion of using alpha for nightly builds with dev.  Thus immediately upon release of 5.0.4 for example, the version should be incremented to: 5.0.5dev1

It may also be appropriate in the init.py to add a comment indicating strict versioning only.

**Comment by butlerpd** [comment]
Of course the above proposal assumes that dev resolves as preceding a which precedes b which precedes rc.  It should based on the description but {a,b,rc} follow the natural lexical order but dev would not so we should probably check this before adopting it.

**Comment by butlerpd** [comment]
This should have been closed with the merging of #1874 but apparently we failed to link it to that PR. Closing it now
