### ISSUE TITLE
Windows failed to execute script sasview if an environment variable HOME exists

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1904]
Sometime shortly after the release of 5.0.1 (Feb 2020) reports started to emerge from both new and existing Users of SasView of a popup displaying _failed to execute script sasview_ when attempting to run the program. Windows users have been the most affected, but not exclusively so. Identifying the cause has been an ongoing saga. The following issues illustrate the challenge:

https://github.com/SasView/sasview/issues/1534
https://github.com/SasView/sasview/issues/1622
https://github.com/SasView/sasview/issues/1672

Some workarounds were identified and added to https://www.sasview.org/faq/#why-will-sasview-no-longer-start but none were a panacea; they worked for some Users, but not others.

User RaffaeleP has now made contact to offer the following insight:
>I recently installed Sasview in Windows 10 and experienced the error “Failed to execute script sasview” when starting the program.The reason for the error is that the installer (for example setupSasView-5.0.4-Win64.exe) and the installed program (sasview.exe) determine the user directory (user_dir) differently. In particular, the installed program sasview.exe determines the user folder by calling expanduser("~") (see function make_user_dir() in src/sas/_config.py), which in turn first looks for the user environment variable HOME: this is not a Windows default variable and, although it is not set by default, it can nevertheless be set as desired. In my case the HOME variable was set during the installation of the program ORCAD and pointed to a subfolder of Orcad itself. Therefore, the installer of Sasview has created a .sasview folder in C:\User\Raffaele, while the installed program sasview.exe, not finding it, has created an additional folder .sasview in the Orcad subfolder. Inside the sasview.log file (created in the Orcad subfolder) the message "ERROR : sas._config (_config.py:94) :: Could not copy default custom config" appears.  After deleting the HOME variable, everything works fine.

I have tested this on a x64/W10 machine happily running both 4.2.2 and 5.0.4. First, I created a new system environment variable HOME and pointed it at C:\Temp. Then I uninstalled 5.0.4 and installed 5.0.3. When I tried to run 5.0.3 it wouldn't start and I got the _failed to execute script sasview_ error. The folder .sasview  and sasview.log were created in C:\Temp. I then deleted the HOME variable, uninstalled 5.0.3, and reinstalled 5.0.4 and tried running 5.0.4. It started normally.

This mismatch should be resolved before the next release.

**Comment by smk78** [comment]
I have updated the FAQ on the website regarding this issue.

**Comment by rozyczko** [comment]
Great to see this issue reproducible! Most likely the installer and SasView itself use differing definitions of HOME. This should and will be standardised.

**Comment by butlerpd** [comment]
There are at least two reproducible separate issues here from what I can tell plus other *mysteries*. I guess we should not pollute all tickets with all problems?  The two reproducible and clear problems now that I see are:
1. `sasview.exe` **cannot ever** copy `custom_config.py`.  Fortunately this only happens when it fails to find an existing `custom_config.py` which should be infrequent since the installer will install one on a clean install and thereafter one should always exist with whatever changes were made by the user. It is however the **immediate** cause of the `Failed to execute script sasview` in all cases I’ve seen so far (evidenced by the entry in the log file as described in a number of places).
2. As @rozyczko  and @AlQuemiste suggest, the installer and the `sasview.exe` program clearly have different definitions for the user directory (I will add results from my further testing in the next comment).  In that sense @AlQuemiste comment now belongs here rather than in #1672, but I guess it is by reference?

#1672 was originally covering 1 but now has a boat load of different observations (including some as yet unresolved issues).  I suggest we open a new ticket with a similar title to #1672 to address point 1 and perhaps change the title of #1672 to represent the more general nature of `sasview.exe` failing to start?  We will then have two addressable issues and one catch all?

**Comment by butlerpd** [comment]
Summary from my testing following @smk78 reporting:

* The installer installs the `.sasview` folder to somewhere that appears to resolve to `C:\Users\[username]\OneDrive` if it exists or if not to `C:\Users\[username]`.  As of 5.0.4 the installer seems to be successfully preventing installation to OneDrive so that it seems to now always resolve to `C\Users\[username]`.
* The installed program `sasview.exe` appears to assume all user information is in the user’s $HOME directory.  This normally seems to resolve to `C:\Users\[username]` which is (coincidentally?) where the immutable system environment “constant” `HOMEPATH` points to (at least in all setups I’ve looked at).  Windows apparently however looks first for the user environment variable `HOME`. If that exists this is what is used and thus may no longer point to the same place.
* NOTE: since the two directories resolve differently there could be other ways they resolve than those discovered so far that could be the cause of other rarely reported problems?

**Question:**
Should the installer install to the generic `home` directory or should the `sasview.exe` program use the mechanism used by INNO and %userprofile% (whatever that is)?

**Data from my testing**
Each of the following tests was preceded by a wiping sasview from the system by uninstalling sasview then manually deleting all `.sasview` and `.sasmodels` folders and sasview.log files I could find.  Then I set `HOME=C:\temp` (which I created previously)
* Installing 5.0.2 the `.sasview` folder was installed either in `C:\User\[username]\OneDrive` if the machine had a OneDrive or in `C:\Users\[username]` on a system without Onedrive.  The `HOME` directory was ignored.
  * In either case running `sasview.exe` caused the “script” error.
  * In the case where `.sasview` was installed to OneDrive, changing the `HOME` environment variable to `C:\Users\[username]\OneDrive` and re-running `sasview.exe` solved the problem.
  * In the case where `.sasview` was installed to `C:\Users\[username]` (OneDrive does not exist on the machine) either changing the `HOME` environment variable to `C:\Users\[username]` or simply deleting it altogether and re-running `sasview.exe` solved the problem.
* Installing 5.0.4 the .sasview folder was **always** installed in the `C:\Users\[username]` regardless of the existence of OneDive **OR** of a `HOME` environment variable.
  * Thus running`sasview.exe` caused the “script” error.
  * Either changing the `HOME` environment variable to `C:\Users\[username]` or simply deleting it altogether and re-running `sasview.exe` solved the problem.

**Comment by butlerpd** [comment]
Is there a SasView code solution to this that can be implemented? or do we close this and post it in the FAQ?

**Comment by rozyczko** [comment]
This can be implemented in SasView. The installer uses %USERPROFILE% and the code should do that but instead it is relying on (among other checks, as @butlerpd noticed), looking at `os.path.expanduser()` which acts weird on systems with defined %HOME%. Using instead `os.environ['USERPROFILE']` for Windows should fix that.

**Comment by lucas-wilkins** [comment]
Think there is still things outstanding here, but could do with having a more well defined ticket - marking as stale

**Comment by butlerpd** [comment]
agreed --
