### ISSUE TITLE
Update scattering calculator documentation

### ISSUE THREAD

**Issue by rjbourne** [SasView/sasview#1918]
After the changes to the generic scattering calculator the user documentation needs to be updated. Progress on this has already been made on the branch https://github.com/SasView/sasview/tree/scattering-calculator-docs, which pertains to PRs #1888 #1898 and #1899. Once all these are merged the docs will need to be reviewed/altered for any changes and then a PR produced.

**Comment by dehoni** [comment]
Artem Feoktystov tested the documentation:

-- There seems one thing missing in the Example 3 (https://github.com/SasView/sasview/blob/scattering-calculator-docs/src/sas/qtgui/Calculators/media/gsc_ex_magnetic_spheres.rst) - in order to generate vtk-file one needs a key "legacy=True" for VTKOutput

-- He generated the vtk-file for R=4 and compared it to the analytical solution and I get 3.47% in the mean error. On the web site you reached 0.165%.

**Comment by dehoni** [comment]
The documentation for vtk file generation has been updated and a note added mentioning that the files were generated using with Netgen 6.2 and that for more recent version a "legacy" flag might be necessary.

 To create the provided vtk files, the mesh refinement has not been performed, hence this line has been deleted. With "mesh.refine" the file size increases 10 fold and resulting in 267960 points to process instead of 34485 points in the current files. In all cases, the "mesh.refine" should appear before curving the resulting meshes. Doing this the max error improves significantly to only 0.226% an the mean error is as low as 0.05%.

**Comment by wpotrzebowski** [comment]
Ok, do I understand correctly that PR associated with this issue is to be created? #1933 doesn't seem to be fully addressing it.

**Comment by dehoni** [comment]
This issue is waiting to see how the Scattering Calculator PR progress. At the moment, [PR #1898](https://github.com/SasView/sasview/pull/1898) for polygonal Fourier transforms is still open. One example (on the magnetic sphere) and the documentation on VTK files relate to it.
