### ISSUE TITLE
Color range slider code needs to change

### ISSUE THREAD

**Issue by rozyczko** [SasView/sasview#1944]
`src\sas\qtgui\Plotting\rangeSlider.py` is an external piece of code and it is GPL-2 licensed.
We strive to be BSD compliant so we can't ship this file. It got implemented back in 2017 as a temporary solution to the problem but reworking it properly has been, of course, forgotten.
Cursory check of similar functionality yields some interesting replacements, e.g.
https://pythonrepo.com/repo/tlambert03-QtRangeSlider-python-graphical-user-interface-applications
and
https://stackoverflow.com/questions/47342158/porting-range-slider-widget-to-pyqt5

This issue should probably be prioritized pretty high.

**Comment by butlerpd** [comment]
So there are choices. And I assume we could subclass the normal single Qtslider and add a second slider to it if we really wanted to do work 😄 

I note however that the first solution (the QtRangeSlider) looks like it will suffer the same problem that @dehoni has encountered: it is integer steps only (unless I miss read that). That said, I think that the sliders probably **should** be integers given they are generic.  What we probably need is a new ticket to fix that slider.  I think the proper fix would be to add code when using the slider that multiplies and/or divides the range we have so that it always has roughly 100 integer steps for the slider? That way regardless of the size of the range there are a reasonable number of steps?

**Comment by butlerpd** [comment]
adding this blocker for now so we don't forget?

**Comment by wpotrzebowski** [comment]
@rozyczko: is this https://pypi.org/project/QtRangeSlider/ any useful?
