### ISSUE TITLE
Cleanup sas.sasview Episode VI: Return of the Cleanup

### ISSUE THREAD

**Issue by lucas-wilkins** [SasView/sasview#2157]
`sas.qtgui` also has a bunch of random stuff in it

![image](https://user-images.githubusercontent.com/9784906/185194805-9c22011c-d5f9-4c30-963a-84b0a25df3d5.png)

**Comment by rozyczko** [comment]
`cyl_400_20.txt`, `Dec*.txt`, `empty_file.txt` and `P123*.dat` are all used in the GUI unit tests.
They have been moved to have a `qtgui` "encapsulated" module without reliance on other parts of the code for testing.
`README.rst` can be removed, since it's, well, old.
`run_tests*` scripts are for running GUI scripts in place. Probably can be removed.
`make_ui*` scripts were used to manually build UIs and can be removed.

**Comment by rozyczko** [comment]
The data files should be removed but the GUI tests referring to them should be then updated.

**Comment by lucas-wilkins** [comment]
Hard to implement this while the tests are failing.
