### ISSUE TITLE
Breaking change in setuptools 50+

### ISSUE THREAD

**Issue by krzywon** [SasView/sasview#2222]
**Describe the bug**

Running GitHub workflow-generated installers on Windows, the following error occurs:
> Traceback (most recent call last):
>   File "sasview.py", line 15, in <module>
>   File "sas\qtgui\MainWindow\MainWindow.py", line 120, in run_sasview
>   File "sas\qtgui\MainWindow\MainWindow.py", line 46, in __init__
>   File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
>   File "sas\qtgui\MainWindow\GuiManager.py", line 14, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
>   File "matplotlib\__init__.py", line 112, in <module>
>   File "_distutils_hack\__init__.py", line 88, in create_module
>   File "importlib\__init__.py", line 127, in import_module
>   File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
>   File "setuptools\__init__.py", line 10, in <module>
>   File "_distutils_hack\__init__.py", line 88, in create_module
>   File "importlib\__init__.py", line 127, in import_module
> ModuleNotFoundError: No module named 'setuptools._distutils'

There is an [issue](https://github.com/pypa/setuptools/issues/2353) in the `setuptools` repo describing the change and potential workarounds, but I haven't read the full thread yet.

**To Reproduce**
Download a recent windows installer generated by a push or PR, install the software, and try to run sasview.

**SasView version (please complete the following information):**
 - Version: post 5.0.5

**Comment by lucas-wilkins** [comment]
You working on this?

**Comment by lucas-wilkins** [comment]
I'm trying using `"setuptools<50"` in `installers.yml` for now.

**Comment by krzywon** [comment]
> You working on this?

Not yet, no. Have at it.

**Comment by lucas-wilkins** [comment]
So, I have tried setting the environment variable `SETUPTOOLS_USE_DISTUTILS` via the iss file, and during creation via installers.yml. Neither work. I've also tried setting the setuputils version in the pip command to <50, that doesn't work either. 

Giving up, at least for today, probably longer.

**Comment by llimeht** [comment]
This is a pair of "pyinstaller" vs "old versions" and "incompatible pinning" issues.

Fortunately, it can be fixed pretty easily in two ways:
 * Force a **newer** `setuptools` into the build. pyinstaller understand setuptools > 65 quite well and if setuptools > 65 is included instead, then it all works. I say "force", because numba has an upper bound on its setuptools version of "< 60" and so pip will downgrade setuptools while installing numba. That downgrade would also be why any of your attempts so far to work around this have failed. Luckily for us, numba doesn't actually need setuptools at runtime at all and that upper bound is relevant only to building numba (and it should be removed!)
 * Getting away from the `matplotlib==2.2.5` that is pinned in the `installers.yml` would also help. The currently supported release of matplotlib (3.5.x) doesn't have any runtime requirement on distutils (and therefore setuptools doing strange things doesn't hurt it). As a bonus, a newer matplotlib will have better support in pyinstaller.

Have I mentioned how much I dislike version pinning recently?

Because pip is pretty dumb in how it handles dependencies, adding `python -m pip install "setuptools>=65"` as the last step of the install step in `installers.yml` will convince it to upgrade setuptools just emitting lots of error messages, but not failing the build.

For example in: https://github.com/SasView/sasview/compare/main...llimeht:sasview:tmp/setuptools-win

I can break that into several PRs if you want, but note that #2216 needs to land first.
