### ISSUE TITLE
Actions: Ubuntu 18.04 deprecation

### ISSUE THREAD

**Issue by krzywon** [SasView/sasview#2398]
**Describe the bug**
My latest push failed CI because the ubuntu-18.04 runs were blocked from running. The following error was given.

> The Ubuntu-18.04 environment is deprecated and will be removed on April 1st, 2023. For more details, see https://github.com/actions/runner-images/issues/6002

**To Reproduce**
See https://github.com/SasView/sasview/actions/runs/3587107236

**Expected behavior**
Due to the deprecation, we should remove ubuntu 18.04 from the CI.

**Comment by llimeht** [comment]
For those who haven't looked yet, this gets updated in `.github/workflows/matrix.py`; there's also a single place in `ci.yml` for testing out the installer where it is listed (that probably wants to be brought into another invocation of `matrix.py` some time).

The release used for the linux pyinstaller is also the oldest release on which it will work; the pyinstaller bundle on linux still uses libc from the host operating system. I'm tempted to recommend leaving 18.04 in place until after the next SasView release for maximum compatibility.

It would make sense to switch to `ubuntu-20.04` for the release builds and `ubuntu-22.04` for also running tests. Keeping a couple of different releases in CI is helpful for early warning of compatibility problems from the unittests, and the ubuntu images are by far the fastest at completing CI so they are good value for this.

Looking at [the list of images](https://github.com/actions/runner-images), I wonder if there's merit in being explicit about the versions and avoiding the movable `-latest` alias.

We should also be thinking about the target Python for the next release. Dropping 3.8 and 3.9 from CI, adding 3.11 to CI and probably picking 3.11 for the next release seems reasonable?

**Comment by rozyczko** [comment]
Python 3.8 EOL is 14 Oct 2024. We should probably still support it. 3.11 is apparently greatly improved in terms of performance so it would be good to have those builds available as well.

I agree 18.04 should be dropped and replaced with 20.04 and we probably should add 22.04 as a separate build. We need to make sure SasView runs on 22.04, since the compatibility between these two is not obvious.

**Comment by llimeht** [comment]
For Python modules that are designed to be reusable components that others would incorporate into their projects, the broadest compatibility makes sense indeed.

For Python applications where the primary focus is a downloadable installer, a much narrower target is common.

Python 3.11's benchmarks are possibly less relevant for sasview since the slowest parts are already in C (via numpy/scipy/sasmodels), but yes, it's an attractive upgrade.

Python 3.11 also comes with a slew of deprecations. Finding and fixing them likely becomes a bit of a priority. `pylint` is quite good at spotting many of them but unfortunately it is incredibly noisy when applied to sasview because it is an historical codebase that has never paid attention to style or pep8/pylint cleanliness. I have been working on a pylintrc that ignores lots of complaints and starts to get the output to a meaningful and actionable level... but pylint actually segfaults on sasview for reasons I can't explain yet. More on that another day!

With the decision to branch off 5.0.6 development, `main` could quite happily ditch Ubuntu 18.04 right now (my previous comment was prior to the branching discussion). A trial run of adding 3.11 makes sense too since that or 3.12 are the obvious targets for the 6.0 release.

**Comment by butlerpd** [comment]
Probably a good discussion point at the next call?
