### ISSUE TITLE
Resolution from 2D file ignored?

### ISSUE THREAD

**Issue by wpotrzebowski** [SasView/sasview#2500]
**Describe the bug**
Testing 5.0.6rc1 on 2D data set that has dQpara and dQperp. I would expect "Smearing" to say "Use dQ data" but it is empty, which may mean that it is not properly read in and subsequently ignored.

**To Reproduce**
1. Load 33837rear_2D_1.75_16.5_NXcanSAS.h5
2. Check what "Smearing" in fitting details says

**SasView version (please complete the following information):**
 - Version: 5.0.6rc1

**Operating system (please complete the following information):**
 - OSX

**Comment by butlerpd** [comment]
I find the same issue on windows 10 (also 5.0.6 rc1) using a different datafile from the test folder (2P_New.sans) which also has the dpar and dperp which are loaded in since they show when choosing `Data Info`  but clearly are ignored when sending to the fitpage. I checked different models as well on the off chance and both sphere and  one of the bicelle models have the same problem (it should not be a model problem but ..)

**Comment by krzywon** [comment]
I don't think this is an issue. `33837rear_2D_1.75_16.5_NXcanSAS.h5` has no Q resolution values in the data set so all `dQpar` and `dQperp` values are 0. The same can be said for `2P_New.sans`.

Loading `SILI010.DAT`, which has q-resolution values defined in the data, works as expected:
![dqx_dqy](https://user-images.githubusercontent.com/10947925/233468814-111cf253-dd7a-4d60-b993-ead98898afc9.png)

**Comment by butlerpd** [comment]
Oops... good point. I got confused because the values are offset from the headers, but yes, looking more carefully, @krzywon is correct that the file I used does NOT have resolution information so behaved as expected.

@wpotrzebowski can we close this issue now?
