### ISSUE TITLE
elipsoid model

### ISSUE THREAD

**Issue by andreashlarsen** [SasView/sasview#2508]
**Describe the bug**
The ellipsoid model fails to fit a simulated 1D dataset of a homogeneous ellipsoid of revolution

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://somo.chem.utk.edu/shape2sas/'
2. Simulate an ellipsoid (e.g. a=b=50, c=100)
3. Download simualted data
4. Fit in SasView with ellipsoid (Category: ellipsoid). 

**Expected behavior**
The model should be consistent with the simulated data

**Screenshots**
![image](https://user-images.githubusercontent.com/29600262/235374017-016f71ae-abc0-45c6-b882-8424b0ab43fb.png)
screenshot showing that sasview ellipsoid model does not fit the simulated data well

![image](https://user-images.githubusercontent.com/29600262/235374105-772b0969-6266-48a5-9821-603506100948.png)
sceenshot showing fit with own python implementation of an ellipsoid of revolution model, as e.g. described in Pedersen (1997) Adv Coll. Interf. Sci 70: 171-200

**SasView version (please complete the following information):**
 - Version: [e.g. 5.0.5]

**Operating system (please complete the following information):**
 - OS: macOS

**Additional context**
own implementation (python3):
 
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit

def sin(x):
    return np.sin(x)

def cos(x):
    return np.cos(x)

def P_elipsoid(q,r1,r2):
    alpha = np.linspace(0,0.5*np.pi,30)
    
    sum = 0
    for a in alpha:
        r = np.sqrt((r1*sin(a))**2 + (r2*cos(a))**2)
        sum += P_sph(q,r)*sin(a)
    sum /= sum[0]
    
    return sum
    
def P_sph(q,r):
    return F_sph(q,r)**2

def F_sph(q,r):
    x=q*r
    return 3*(sin(x)-x*cos(x))/x**3
    
def ellipsoid(q,r1,r2,s,b):
    return s*P_elipsoid(q,r1,r2)+b

q,I,sigma = np.genfromtxt('Isim_ellipsoid_r150_r2100.dat',skip_header=3,unpack=True)

popt,pcov = curve_fit(ellipsoid,q,I,sigma=sigma,p0=[50,100,1,0])
fit = ellipsoid(q,*popt)

R = (I-fit)/sigma
chi2 = np.sum(R**2)
chi2r = chi2/(len(q)-len(popt))

plt.errorbar(q,I,yerr=sigma,linestyle='none',marker='.',color='red',zorder=0,label='simulated data, ellipsoid (R1=50, R2=100)')
plt.plot(q,fit,color='black',zorder=1,label='fit,ellipsoid, R1 = %1.1f, R2 = %1.1f, chi2r=%1.1f' % (popt[0],popt[1],chi2r))
#plt.xscale('log')
plt.yscale('log')
plt.xlabel('q')
plt.ylabel('I')
plt.legend(frameon=False)
plt.savefig('fit')
plt.show()

**Comment by butlerpd** [comment]
A quick look at the shape of the curve and verifying with sasview (from head basically) suggests that the simulations is for a prolate rather than an oblate ellipsoid? I note that the parameters entered in SasView above are for an oblate ellipsoid. If you reverse the entries so that 100 is the polar and 50 is the equatorial radius the shape of the resulting curve is much more similar to the simulation. I have not had time to test following the whole procedure but thought I'd mention what I see sooner than later?

In the meantime, I see that the documentation for ellipsoid needs some work. At the least there should be a diagram showing visiually what Rp and Re are. Also the "validation" looks very dubious to me. That should be updated. Actually, for consistency, it can probably just be removed (very few models have that section and it is not clear that it brings that much). However, before doing so, we might want to do some more validation ... which @andreashlarsen is effectively starting here 😄.

Finally, I note this is really a sasmodels issue not a sasview issue. We should probably move the issue to the sasmodels repo?

**Comment by lucas-wilkins** [comment]
I've looked into this too. The entries are indeed the wrong way round.

**Comment by andreashlarsen** [comment]
Ah! It makes sense that the algorithm did not find the minumum, as I had typed in the initial guesses the wrong way around. After providing better initial guesses, the fit is as expected. Thank you, @lucas-wilkins, @butlerpd.
<img width="1382" alt="Screenshot 2023-05-01 at 09 21 12" src="https://user-images.githubusercontent.com/29600262/235422137-efa9a219-3695-4c35-83da-c683e742afe0.png">

@butlerpd : yes, would be a good help with an illustration of the model, indicating radii. I made this, which might be helpful for other users:
[ellipsoid.pdf](https://github.com/SasView/sasview/files/11364214/ellipsoid.pdf)

**Comment by butlerpd** [comment]
That's perfect @andreashlarsen. It will need to be converted to a PNG I think and then can be added to the media folder and used when updating the documentation on the ellipsoid model. The documentation is in fact part the ellipsoid.py python file all of which is in sasmodels. I'll try to move the relevant parts of this discussion into a defect issue in the sasmodels repo.

**Comment by andreashlarsen** [comment]
png format.
![ellipsoid](https://user-images.githubusercontent.com/29600262/235689623-8b5be21b-01e8-4c26-b250-da203c015291.png)
