### ISSUE TITLE
Upgrade to the latest version of the upload-artifact action

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#2811]
While the `actions/upload-artifact` and `actions/download-artifact` actions do not contain deprecated calls there is now a new version of the action which promises significant performance improvements which may be of interest to us. However they also point out these are breaking changes and in particular that artifacts created with version 3 of the download **CANNOT** be uploaded by version 4.

I recommend we move to this after release 6.0.0 to avoid any unnecessary extra issues to follow?

From the release pages for the new version (version 4.x) 

> The release of upload-artifact@v4 and download-artifact@v4 are major changes to the backend architecture of Artifacts. They have numerous performance and behavioral improvements.

> However, this is a major update that includes breaking changes. Artifacts created with versions v3 and below are not compatible with the v4 actions. Uploads and downloads must use the same major actions versions. There are also key differences from previous versions that may require updates to your workflows.

**Comment by rozyczko** [comment]
We had to downgrade to v3, due to a breaking change affecting our projects. The new upload doesn't allow replacing existing files with the same name. This is bad for cases when you have more than one build per branch or per release.
https://github.com/actions/upload-artifact/issues/478
It seems there is some work being done so maybe this is moot by now, just making sure we check it properly when upgraded.
