### ISSUE TITLE
Ubuntu (latest) tests failing

### ISSUE THREAD

**Issue by klytje** [SasView/sasview#2812]
The CI system for Ubuntu (latest) currently fails when installing the X11 libraries, or more specifically the `libegl-dev` library ([case 1](https://github.com/SasView/sasview/actions/runs/7972097994/job/21765907856#step:5:64), [case 2](https://github.com/SasView/sasview/actions/runs/7934612039/job/21665970452)),  Going through the error report reveals that the cached download link (http://security.ubuntu.com/ubuntu/pool/main/m/mesa/libegl-mesa0_23.0.4-0ubuntu1%7e22.04.1_amd64.deb) is dead since the library has been updated. 

I've solved the issue in my own PR by adding a simple `sudo apt-get update` before attempting to download the libraries, but I don't know enough about the CI system to know if this is a good solution.

**Comment by llimeht** [comment]
Interesting finds!

> I've solved the issue in my own PR by adding a simple `sudo apt-get update` before attempting to download the libraries, but I don't know enough about the CI system to know if this is a good solution.

Yes, that's a reasonable solution to handle security updates having been pushed out but the base images haven't been regenerated recently.

Perhaps a quick PR just for that change so that it can be merged and CI works for everyone would be worthwhile?

> Bonus info I discovered while checking previous CI runs: The Try running the installation (Linux) step hasn't been working for months due to a missing EGL library:

I assume that's a related problem that a package wasn't installed as desired or perhaps the library location changed between releases. Do you know what the right package is for the current Ubuntu images?

Yes, we should also do better in that testing... it's supposed to fail as you say. Could you please file a separate issue for that one so we don't forget?

**Comment by klytje** [comment]
I implemented the changes in PR #2814, but it seems like the issue have solved itself. Should we merge it in anyway to prevent similar issues in the future?

**Comment by llimeht** [comment]
Thanks @klytje! Yes, it's still worth fixing because it will happen again next time there is a delay between a security update coming out for packages used in CI and the images being regenerated.
