### ISSUE TITLE
Which version does the Zenodo DOI refer too?

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#2906]
Copied from https://github.com/SasView/sasview/issues/2898

**Describe the bug**
The acknowledge popup shows version 6.0.0b1, DOI. 
Should that DOI be xxx for an alpha and beta? or are we really providing a different doi for these?

**Comment by smk78** [comment]
Are we sure the zenodo identifier (10.5281/zenodo.11395968) is correct? Because it doesn't resolve! (This might also explain why some of the other recent versions don't show up on Zenodo?)

**Comment by butlerpd** [comment]
Having spoken to @krzywon, I believe it doesn't resolve because that will be the DOI for the final 6.0.0 release which does not yet exist. To some extent this is a beta ... but it still seems wrong to put a DOI in the distributed code (the beta in this case) that does not actually represent the code that DOI is (or will in this case) point to?

**Comment by lucas-wilkins** [comment]
Shall we close this if its actually ok? @krzywon

**Comment by krzywon** [comment]
Future versions of beta releases should have separate DOIs, but for 6.0.0 release, the betas and final release will share a single DOI.
