### ISSUE TITLE
Data Operation Tool does not scale a dataset (Trac #186)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#334]
The Data Operation Tool allows for a dataset to be multipled by a number, the default multiplier being 1.0.

However, whilst changing this multiplier and clicking apply generates a new SasView dataset, either no multiplier is applied, or the value applied is just 1.0.

Reported by Arnauld Poulesquen, 14/05/2013.

Migrated from http://trac.sasview.org/ticket/186
```json
{
    "status": "closed",
    "changetime": "2016-08-12T14:27:26",
    "_ts": "2016-08-12 14:27:26.564603+00:00",
    "description": "The Data Operation Tool allows for a dataset to be multipled by a number, the default multiplier being 1.0.\n\nHowever, whilst changing this multiplier and clicking apply generates a new SasView dataset, either no multiplier is applied, or the value applied is just 1.0.\n\n\nReported by Arnauld Poulesquen, 14/05/2013.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView GUI Redesign",
    "time": "2013-05-14T15:15:35",
    "component": "SasView",
    "summary": "Data Operation Tool does not scale a dataset",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "lewis",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2013/08/31 17:53:56`: 
* **butler** commented:

Upon further investigation the problem is that currently the user must hit enter after entering a number before applying.  Just clicking in a different box won't do it.  Clearly want a better updating mechanism, but the functionality does work so downgrading the urgency.  The number being multiplied is shown in the big box (where data shows up if adding a data set rather than a number) and is the exact number that will be applied.

Clearly the whole interface and logic was designed with two data sets in mind and the scaler option added later by user demand.  Would be nice to make the usage more transparent


* **butler** changed milestone from "" to "WishList"
* **butler** changed priority from "critical" to "minor"

**Comment by ajj** [comment]
Trac update at `2015/01/14 12:37:23`: **ajj** changed workpackage from "" to "SasView Bug Fixing"

**Comment by butlerpd** [comment]
Trac update at `2015/03/15 02:03:25`: **butler** changed workpackage from "SasView Bug Fixing" to "SasView GUI Redesign"

**Comment by butlerpd** [comment]
Trac update at `2016/08/12 14:27:26`: **butler** changed milestone from "WishList" to "SasView 4.0.0"
