### ISSUE TITLE
Fitting pespective not loading (Trac #198)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#346]
Build r6846 run on a clean mac does not successfully load the fitting module because:

2014-01-19 20:17:28,518 ERROR Fitting problems: CategoryInstaller: Could not find folder containing default categories
2014-01-19 20:17:28,518 ERROR SasView: could not find Fitting plug-in module
2014-01-19 20:17:28,518 ERROR CategoryInstaller: Could not find folder containing default categories

(from sasview.log)

Migrated from http://trac.sasview.org/ticket/198
```json
{
    "status": "closed",
    "changetime": "2014-01-29T18:21:26",
    "_ts": "2014-01-29 18:21:26.940237+00:00",
    "description": "Build r6846 run on a clean mac does not successfully load the fitting module because:\n\n2014-01-19 20:17:28,518 ERROR Fitting problems: CategoryInstaller: Could not find folder containing default categories\n2014-01-19 20:17:28,518 ERROR SasView: could not find Fitting plug-in module\n2014-01-19 20:17:28,518 ERROR CategoryInstaller: Could not find folder containing default categories\n\n(from sasview.log)\n\n",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "time": "2014-01-19T19:20:55",
    "component": "SasView",
    "summary": "Fitting pespective not loading",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 3.0.0",
    "owner": "butler",
    "type": "defect"
}
```

**Comment by ajj** [comment]
Trac update at `2014/01/19 19:22:37`: **ajj** changed milestone from "SasView 3.0.0" to "SasView Next Release"

**Comment by butlerpd** [comment]
Trac update at `2014/01/19 20:07:48`: **butler** changed milestone from "SasView Next Release" to "SasView 3.0.0"

**Comment by butlerpd** [comment]
Trac update at `2014/01/19 21:27:47`: 
* **butler** commented:

Old title: Categories broken in current mac build

This is a general problem not mac only.  I just installed on a clean windows 8.1 machine and found exact same errors in the logfile.  

NOTE: THIS PREVENTS FITTING FROM LOADING. In other words the applications starts and does not crash on those errors but the fitting perspective is disabled so that when you go to choose fitting (rather than say P(r) ) no such thing is possible.  This may be related to the problem Jeff is having on the datainfo and the reader.

The default_category file is in the sasview directory as it should be.  Since nothing has been touched in the repository regarding categories, this may be left over from the code reorg project.  With luck it is just a setup.py fix.


* **butler** changed priority from "major" to "blocker"
* **butler** changed summary from "Categories broken in current mac build" to "Fitting pespective not loading"

**Comment by ajj** [comment]
Trac update at `2014/01/19 23:23:46`: 
* **ajj** changed _comment0 from:

> If I do:
> 
> python setup.py install --user 
> 
> and then run the script that is installed (~/Library/Python/2.7/bin/sasview in the case of my Mac) then all is well. Running the packaged app build fails to load the fitting perspective. 
> 
> Is this then a bundling issue?

to:

> 1390173848816718


* **ajj** commented:

If I check out the source and do:

python setup.py install --user 

and then run the script that is installed (~/Library/Python/2.7/bin/sasview in the case of my Mac) then all is well. Running the packaged app build fails to load the fitting perspective. 

Is this then a bundling issue?

**Comment by mdoucet** [comment]
Trac update at `2014/01/21 19:20:50`: 
* **mathieu** commented:

For the Mac build, the problem was that py2app is zipping site-packages before putting it in the app directory.
Added the following to the build script:


```text
unzip -q sasview.app/Contents/Resources/lib/python2.6/site-packages.zip -d sasview.app/Contents/Resources/lib/python2.6
```

Also made sure that the ```--always-unzip``` option is used when calling easy_install on the sasview package.



* **mathieu** changed resolution from "" to "fixed"
* **mathieu** changed status from "new" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2014/01/28 14:53:21`: 
* **butler** commented:

The windows app is still broken.  After discussion at today's meeting am re-opening and tentatively assigning to Peter Parker.


* **butler** changed resolution from "fixed" to ""
* **butler** changed status from "closed" to "reopened"
