### ISSUE TITLE
Provide for Kratky representation of data (Trac #205)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#353]
Modify Graph -> Change Scale -> Properties dialog, and provide
underlying code to allow a Kratky representation (Q^2^.I(Q) vs Q) of
the data.

Whilst of general use, this is particularly useful for establishing
if the data is suitable for Invariant integration; ie, if the integral
is open or closed.

Migrated from http://trac.sasview.org/ticket/205
```json
{
    "status": "closed",
    "changetime": "2016-08-11T14:20:44",
    "_ts": "2016-08-11 14:20:44.782411+00:00",
    "description": "Modify Graph -> Change Scale -> Properties dialog, and provide\nunderlying code to allow a Kratky representation (Q^2^.I(Q) vs Q) of\nthe data.\n\nWhilst of general use, this is particularly useful for establishing\nif the data is suitable for Invariant integration; ie, if the integral\nis open or closed.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView GUI Enhancements",
    "time": "2014-02-14T09:45:21",
    "component": "SasView",
    "summary": "Provide for Kratky representation of data",
    "priority": "critical",
    "keywords": "Graph, Kratky, Invariant",
    "milestone": "SasView 4.0.0",
    "owner": "ajj",
    "type": "enhancement"
}
```

**Comment by smk78** [comment]
Trac update at `2014/02/14 09:47:15`: **smk78** commented:

Oops, sorry about the wiki formatting! That should say (Q-squared.I(Q)) vs Q.

**Comment by butlerpd** [comment]
Trac update at `2014/04/01 15:39:25`: 
* **butler** changed owner from "" to "ajj"
* **butler** changed status from "new" to "assigned"

**Comment by smk78** [comment]
Trac update at `2014/04/01 16:43:10`: 
* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "assigned" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2016/07/10 16:31:57`: 
* **butler** changed _comment0 from "Am reopening this ticket as it is not working at the moment.  A kratky option is provided but no q^2^I(q) option for the y axis and !PlotPanel.py does not know about this view so is ignored (worse it raises a traceback error).  It needs to be added in !PropertyDialog.py and !PlotPanel.py.  It may also need to be added to transform.  Finally, it would be good to be able to plot reduced Kratky (qRg rather than q) but this can wait. For release 4.0 we either need to fix the basic Kratky or remove it as an option (since it cannot have worked before that should be fine ... though should double check that is true of 3.1.2 before choosing this option)." to "1468171798292509"
* **butler** commented:

Am reopening this ticket as it is not working at the moment.  A kratky option is provided but no q^2^I(q) option for the y axis and !PlotPanel.py does not know about this view so is ignored (worse it raises a traceback error).  It needs to be added in !PropertyDialog.py and !PlotPanel.py.  It may also need to be added to transform.  Finally, it would be good to be able to plot reduced Kratky (qRg rather than q) but this can wait. For release 4.0 we either need to fix the basic Kratky or remove it as an option. Since it did not work before either (checked 3.1.2) that should be fine as well (though not ideal of course)


* **butler** changed description from:

> Modify Graph -> Change Scale -> Properties dialog, and provide
> underlying code to allow a Kratky representation (Q^2.I(Q) vs Q) of
> the data.
> 
> Whilst of general use, this is particularly useful for establishing
> if the data is suitable for Invariant integration; ie, if the integral
> is open or closed.

to:

> Modify Graph -> Change Scale -> Properties dialog, and provide
> underlying code to allow a Kratky representation (Q^2^.I(Q) vs Q) of
> the data.
> 
> Whilst of general use, this is particularly useful for establishing
> if the data is suitable for Invariant integration; ie, if the integral
> is open or closed.


* **butler** changed milestone from "SasView 3.0.0" to "SasView 4.0.0"
* **butler** changed priority from "minor" to "critical"
* **butler** changed resolution from "fixed" to ""
* **butler** changed status from "closed" to "reopened"
* **butler** changed workpackage from "" to "SasView GUI Enhancements"

**Comment by smk78** [comment]
Trac update at `2016/08/11 14:17:14`: **smk78** commented:

In [https://github.com/lewisodriscoll/sasview/commit/8abd96d6ebdf20551265a5a33a9fd0d56ebe5584 8abd96d6ebdf20551265a5a33a9fd0d56ebe5584] Lewis says:

Fixing the error bar calculations also removes the need to scale the y axis when changing to a Porod or Kratky plot, so commit f2f6af9 has effectively been reverted.

**Comment by smk78** [comment]
Trac update at `2016/08/11 14:18:12`: **smk78** commented:

In [https://github.com/lewisodriscoll/sasview/commit/b2f21e0d2280f5fd1cbb854d2c045b937ca32f94 b2f21e0d2280f5fd1cbb854d2c045b937ca32f94] Lewis says:

Fix LaTeX formating of labels when scale changed

**Comment by smk78** [comment]
Trac update at `2016/08/11 14:19:29`: **smk78** commented:

In [https://github.com/lewisodriscoll/sasview/commit/51296869a9635f6bbe7ea2bf9ea57b2f5ee095cf 51296869a9635f6bbe7ea2bf9ea57b2f5ee095cf] Lewis says:

Make !PropertyDialog !ComboBoxes read-only.

Also set scale values automatically when the user chooses a view, making
some of the logic in !PlotPanel redundant

**Comment by smk78** [comment]
Trac update at `2016/08/11 14:20:32`: **smk78** commented:

In [https://github.com/lewisodriscoll/sasview/commit/1ed6be74dd086a570674b6acb2a8d3c7fa0bf36d 1ed6be74dd086a570674b6acb2a8d3c7fa0bf36d] Lewis says:

Fix units on Kratky plot

**Comment by smk78** [comment]
Trac update at `2016/08/11 14:20:44`: 
* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "reopened" to "closed"
