### ISSUE TITLE
Default "load data" directory to the last one used (Trac #230)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#378]
Migrated from http://trac.sasview.org/ticket/230
```json
{
    "status": "closed",
    "changetime": "2017-04-06T09:51:58",
    "_ts": "2017-04-06 09:51:58.562443+00:00",
    "description": "",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView GUI Enhancements",
    "time": "2014-04-03T10:10:37",
    "component": "SasView",
    "summary": "Default \"load data\" directory to the last one used",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment]
Trac update at `2014/04/05 20:55:41`: 
* **butler** commented:

This is supposed to work and code looks like it should work but it doesn't always do so. 


* **butler** changed milestone from "SasView 3.0.0" to "SasView Next Release +1"

**Comment by ajj** [comment]
Trac update at `2015/01/14 12:37:23`: **ajj** changed workpackage from "" to "SasView Bug Fixing"

**Comment by butlerpd** [comment]
Trac update at `2015/02/01 23:05:50`: **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1"

**Comment by butlerpd** [comment]
Trac update at `2015/03/10 16:54:54`: 
* **butler** commented:

We need to agree on what we want as the new interface for this.  Probably a real preferences window that lets one enter values for the items set in the configuration file (at least those we will allow the user to change).  That however will be a major undertaking so probably not for this release.  Hence moving from 3.1 to next + 1


* **butler** changed milestone from "SasView 3.1" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2015/03/22 22:54:28`: 
* **butler** changed type from "defect" to "enhancement"
* **butler** changed workpackage from "SasView Bug Fixing" to "SasView GUI Enhancements"

**Comment by ajj** [comment]
Trac update at `2017/04/04 21:56:47`: **ajj** commented:

This seems to be working? Is it fixed?

**Comment by butlerpd** [comment]
Trac update at `2017/04/05 21:21:19`: **butler** commented:

Would be very happy to get a consensus and close this but absolutely nothing has changed since the ticket was first written.  The problem is one of choosing the expected behavior.  currently (as it has for a long time) the last directory from which a file was loaded is the default directory for the next load.  However, it does not persist from session to session unless the new default directory is saved by clicking View ->Startup Settings and choosing "current View"

If it should persist without that then we should change that menu and also the behavior. I am all in favor of that but since the ticket was raised by someone else....

Ultimately (mainly in new GUI?) we should probably replace that clunky mechanism with a proper setting page.

**Comment by ajj** [comment]
Trac update at `2017/04/06 09:51:58`: 
* **ajj** changed resolution from "" to "fixed"
* **ajj** changed status from "new" to "closed"
