### ISSUE TITLE
Box integration does not update when entering values in dialog (Trac #260)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#408]
If you change the parameters of a box integration from the dialog box, the results don't update i.e. the calculation is not performed when values are manually entered.

Dragging the handles on the plot does update the values.

Migrated from http://trac.sasview.org/ticket/260
```json
{
    "status": "closed",
    "changetime": "2017-10-26T11:19:13",
    "_ts": "2017-10-26 11:19:13.778400+00:00",
    "description": "If you change the parameters of a box integration from the dialog box, the results don't update i.e. the calculation is not performed when values are manually entered.\n\nDragging the handles on the plot does update the values.",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2014-05-18T18:57:22",
    "component": "SasView",
    "summary": "Box integration does not update when entering values in dialog",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2014/05/18 19:52:47`: **butler** commented:

Actually, on the PC at least, as with many wx boxes you must hit enter for the new value to be accepted.  This should be added as a known issue I gues?  Testing seems to work on my PC.  HOWEVER -- two other things pop up.  First using the section slicer I was able to freeze the graph once.... but not able to reproduce.  This suggests there is a small bug somewhere and the code should get a close look.

Annoyingly the handles can disappear if the typed in parameters put them outside the graph making it difficult to manualy grab (can be fixed by going back to the manual edits and changing the size to bring the handles back into range)

**Comment by ajj** [comment]
Trac update at `2015/01/14 12:37:23`: **ajj** changed workpackage from "" to "SasView Bug Fixing"

**Comment by rozyczko** [comment]
Trac update at `2017/04/08 19:42:38`: **piotr** commented:

This has been properly implemented in the qt version.

**Comment by butlerpd** [comment]
Trac update at `2017/10/26 11:19:13`: 
* **butler** changed milestone from "SasView Next Release +1" to "SasView 4.2.0"
* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "new" to "closed"
