### ISSUE TITLE
Investigate why Image Viewer tool is not loading .TIF or .BMP (Trac #265)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#413]
Paul said on 31 May:

It seems that jpg, png, and gif work but that bmp and tiff currently 
do not.  

Migrated from http://trac.sasview.org/ticket/265
```json
{
    "status": "closed",
    "changetime": "2015-02-18T17:31:14",
    "_ts": "2015-02-18 17:31:14.794689+00:00",
    "description": "Paul said on 31 May:\n\nIt seems that jpg, png, and gif work but that bmp and tiff currently \ndo not.  ",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2014-05-31T12:50:20",
    "component": "SasView",
    "summary": "Investigate why Image Viewer tool is not loading .TIF or .BMP",
    "priority": "critical",
    "keywords": ".TIF, .BMP, File Extension",
    "milestone": "SasView 3.1.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2014/05/31 15:33:31`: **butler** commented:

On further investigation, this works on my development system (windows 8.1 laptop with packages as given in ticket #361 [raw-attachment:sasview-dependencies-survey.pdf:ticket:213 Table]. It does not work however in the exe bundle.

imageviewer.py in the guiframe package seems to be doing the work and is using matplotlib.image.imread to load the files. My matplotlib is 1.3 instead of the 1.1. on the build system.  However this code was introduced by Jae Hie about a year ago (probably using 0.98?)  so not likly to be cuplrit?  Looking for dependencies that might be a problem I found an article which suggests that only PNG is  natively supported by matplotlib and that the other formats rely on PIL -- but my system (which works) does not have PIL while the build system (which seems not to work) does have PIL.

**Comment by butlerpd** [comment]
Trac update at `2014/05/31 15:33:45`: **butler** changed milestone from "SasView Next Release +1" to "SasView 3.0.1"

**Comment by ajj** [comment]
Trac update at `2015/01/14 12:37:22`: **ajj** changed workpackage from "" to "SasView Bug Fixing"

**Comment by mdoucet** [comment]
Trac update at `2015/02/18 16:51:38`: **mathieu** commented:

The images load on my Mac. The only problem I have is that the wildcards used in the dialog won't let you select any file. All files on the Mac file dialog are grayed out and there's no way to change the file extension filter. Apparently the support for wildcards isn't great with wx (at least according to their docs). I'll change it to load any file, but with better error catching (there is none at the moment).

**Comment by mdoucet** [comment]
Trac update at `2015/02/18 17:31:14`: 
* **mathieu** changed resolution from "" to "fixed"
* **mathieu** changed status from "new" to "closed"
