### ISSUE TITLE
Survey current SasView infrastructure

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#438]
To minimise the proliferation of resources we are using we should try to merge the website and trac etc to be integrated and hosted together.

Migrated from http://trac.sasview.org/ticket/303
```json
{
    "status": "accepted",
    "changetime": "2017-04-04T21:55:54",
    "_ts": "2017-04-04 21:55:54.654807+00:00",
    "description": "To minimise the proliferation of resources we are using we should try to merge the website and trac etc to be integrated and hosted together.\n\n",
    "reporter": "ajj",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Admin",
    "time": "2015-02-12T09:28:09",
    "component": "SasView",
    "summary": "Integrate user and developer websites",
    "priority": "minor",
    "keywords": "",
    "milestone": "Admin Tasks",
    "owner": "ajj",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/06/19 15:18:21`: **butler** commented:

Integration and "hosting together" are not the same thing, and after thinking a lot about this and researching not sure that it is possible to do the second or more to the point is perhaps not in fact the most desirable way to achieve integration.  Indeed there are many services that integrate with !GitHub some deeply others not so deep.

I think the real "requirements" are simply:
* The users and particularly developers shouldn't need to remember a gazilion URLs and more importantly NOT have to remember a gazilion username passwords.  In that vein I note that !GitHub uses OAut server which can be used and that trac has an add on that allows both redirecting the "browse repo" to !GitHub and uses the !GitHub login?  What I don't know how to do but is clearly doable given some of the third party add-ons seem to do it (see for example zenhub https://github.com/integrations/zenhub) is to add options on the !GitHub page that links directly to our external wiki and tickets rather than their issues and wiki which are really simplified at this point?  Of course Zenhub is supposed to make those very features not so lame but not clear to me that is good enough yet.
* As much as possible we want hosted solutions that do not require a huge amount of our efforts to maintain while keeping in mind the above requirment.  In that vein there are a lot of tools that integrate at one level or another that can be found at https://github.com/integrations.  Most of the free services do not support windows builds yet unfortunately and most of the full life cycle suites are for fee - but at some point we may want to think about getting a small amount of real support for this kind of thing.

**Comment by ajj** [comment]
Trac update at `2017/04/04 21:55:54`: 
* **ajj** commented:

Should look at option of using "login with Github" or such for Trac - might need some more developer groups if so.


* **ajj** changed owner from "" to "ajj"
* **ajj** changed status from "new" to "accepted"

**Comment by ajj** [comment]
This issue is probably obsolete, but can serve as a pointer to having a survey of our current infrastructure status. Renamed accordingly.

Need to survey the infrastructure and determine where the weaknesses are/where improvements can be made and create tickets accordingly

**Comment by lucas-wilkins** [comment]
> This issue is probably obsolete

Should be closed then!

**Comment by butlerpd** [comment]
agreed. I believe only @ajj and I were working/thinking about this so I think I can take responsibility for closing.
