### ISSUE TITLE
Check all models for order of parameters being passed (Trac #361)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#496]
Migrated from http://trac.sasview.org/ticket/361
```json
{
    "status": "closed",
    "changetime": "2016-03-20T12:03:28",
    "_ts": "2016-03-20 12:03:28.628724+00:00",
    "description": "",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasModels Redesign",
    "time": "2015-02-20T14:29:14",
    "component": "SasView",
    "summary": "Check all models for order of parameters being passed",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "richardh",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/08/14 19:54:17`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.0.0"

**Comment by butlerpd** [comment]
Trac update at `2016/03/06 18:05:24`: 
* **butler** commented:

This should be part of sasmodels to first order.  In fact order is given by order declared in parameter block.  Should verify some standard probably?  Otherwise maybe we are done? verify with Andrew if he remembers if there was more to this ticket since he submitted.

Meanwhile changing to Blocker on grounds it is part of core sasmodels work for this release


* **butler** changed priority from "major" to "blocker"

**Comment by butlerpd** [comment]
Trac update at `2016/03/06 23:11:39`: 
* **butler** changed owner from "" to "richardh"
* **butler** changed status from "new" to "assigned"

**Comment by ajj** [comment]
Trac update at `2016/03/20 12:03:28`: 
* **ajj** changed resolution from "" to "fixed"
* **ajj** changed status from "assigned" to "closed"
