### ISSUE TITLE
Mac build requesting git install when run (Trac #416)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#550]
On running the latest mac build, a Mac OS dialog appears requesting the installation of git command line tools. 

Migrated from http://trac.sasview.org/ticket/416
```json
{
    "status": "closed",
    "changetime": "2015-05-24T00:37:09",
    "_ts": "2015-05-24 00:37:09.356966+00:00",
    "description": "On running the latest mac build, a Mac OS dialog appears requesting the installation of git command line tools. \n",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-05-15T19:37:15",
    "component": "SasView",
    "summary": "Mac build requesting git install when run",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/05/15 22:22:49`: **butler** commented:

This may be due to help pointing to git repo for bumps documentation.  Visiting with Mathieu we noticed that no documentation populates the help windows they stay blank. On PC version (downlaoded) they to work but I noticed the bumps documents send you to github and do not render the math and links.  Before entering another ticket at this point we should see if these are not all linked I guess.

**Comment by butlerpd** [comment]
Trac update at `2015/05/24 00:37:09`: 
* **butler** commented:

After removing the git call to pull the build number in (doesn't work for the distribution code) this seems to be resolved.  Also removes the git error being reported in the windows log file).


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "new" to "closed"
