### ISSUE TITLE
Plot limits connection to plot is totally screwed up (Trac #417)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#551]
When clicking on the q limit box the corresponding fit panel brings up two vertical lines (red and green) that show the current qmin and qmax for the fit and move when numbers are changed in box.  Also they can be grabbed and moved to change the fit limits.  

However, in the latest version (build 173 on PC - needs testing on mac), clicking in the limits boxes causes the associated plot to rescale the qmin down by very many orders of magnitude so that all the data and both red and green lines are on the right hand edge of the plot and neither visible nor accessible.  

Migrated from http://trac.sasview.org/ticket/417
```json
{
    "status": "closed",
    "changetime": "2015-06-03T17:41:09",
    "_ts": "2015-06-03 17:41:09.048314+00:00",
    "description": "When clicking on the q limit box the corresponding fit panel brings up two vertical lines (red and green) that show the current qmin and qmax for the fit and move when numbers are changed in box.  Also they can be grabbed and moved to change the fit limits.  \n\nHowever, in the latest version (build 173 on PC - needs testing on mac), clicking in the limits boxes causes the associated plot to rescale the qmin down by very many orders of magnitude so that all the data and both red and green lines are on the right hand edge of the plot and neither visible nor accessible.  ",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-05-17T18:52:09",
    "component": "SasView",
    "summary": "Plot limits connection to plot is totally screwed up",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "butler",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/05/31 18:19:21`: 
* **butler** changed owner from "" to "butler"
* **butler** changed status from "new" to "accepted"

**Comment by pkienzle** [comment]
Trac update at `2015/06/03 17:41:09`: 
* **pkienzle** commented:

Putting the vertical line on the plot outside the range of the data resets the plot x range in the latest version of matplotlib.  The patch forces the bars to line within the range of the data, even if the min/max given in the q range is outside the data.

The text widget is not updated with the actual bar position since that would make it difficult to enter a value such as 0.01, which first requires entering the value of zero, which is beyond the minimum q value.


* **pkienzle** changed resolution from "" to "fixed"
* **pkienzle** changed status from "accepted" to "closed"
