### ISSUE TITLE
allow constraints on batch fits (Trac #425)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#559]
Batch fitting currently sets the constraints menu as disabled.  There is no reason not to enable it now that we are using bumps, but the UI for the constraints screen may need to change.  Haven't looked at the code yet.

Migrated from http://trac.sasview.org/ticket/425
```json
{
    "status": "new",
    "changetime": "2015-06-10T14:53:05",
    "_ts": "2015-06-10 14:53:05.367425+00:00",
    "description": "Batch fitting currently sets the constraints menu as disabled.  There is no reason not to enable it now that we are using bumps, but the UI for the constraints screen may need to change.  Haven't looked at the code yet.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Fitting Redesign",
    "time": "2015-06-10T14:53:05",
    "component": "SasView",
    "summary": "allow constraints on batch fits",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by gonzalezma** [comment]
Now (at least with release 6.0.0), it is possible to use constraints (within a single data set) also in the batch fitting. It is not immediately intuitive, because one needs to call the Constrained or Simultaneous Fit page to define the constraints, but then one must use the Fit button in the BatchPage to do the fit, but it works. So I am closing this and will create an issue to document this feature.
