### ISSUE TITLE
DREAM subplot configuration window is blank (Trac #449)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#583]
ESS Win 7 Version 3.1.0 Build 124

Clicking the Subplot icon below any of the plots in the DREAM Fit Result Panel launches a sub-window called Configure subplots. This sub-window is blank!

HOWEVER... depending where you click in the sub-window interesting things happen to the selected plot in the Fit Result Panel. The only problem is I have yet to find where to click to reset the plot!!!

Migrated from http://trac.sasview.org/ticket/449
```json
{
    "status": "closed",
    "changetime": "2015-07-13T15:57:03",
    "_ts": "2015-07-13 15:57:03.288065+00:00",
    "description": "ESS Win 7 Version 3.1.0 Build 124\n\nClicking the Subplot icon below any of the plots in the DREAM Fit Result Panel launches a sub-window called Configure subplots. This sub-window is blank!\n\nHOWEVER... depending where you click in the sub-window interesting things happen to the selected plot in the Fit Result Panel. The only problem is I have yet to find where to click to reset the plot!!!",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-07-07T16:51:31",
    "component": "SasView",
    "summary": "DREAM subplot configuration window is blank",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/07/10 14:46:09`: **butler** commented:

The subplot button is one of the default matplot lib toolbar items.  However, !SasView completely overides that in plottools.toolbar.py.  In that we remove the subplot button (not sure why but maybe we now know?)  Bumps is using the matplot lib default.  However I would have thought that since we overide in the application it should overide for BUMPS as well ... but maybe the overide would have to be at a higher level if BUMPS doesn't go through plottools?

**Comment by ajj** [comment]
Trac update at `2015/07/10 21:34:41`: **ajj** commented:

The subplot button and configuration panel work correctly on Mac (10.10.4). Don't think this should be a blocker for 3.1

**Comment by pkienzle** [comment]
Trac update at `2015/07/13 15:57:03`: 
* **pkienzle** changed resolution from "" to "fixed"
* **pkienzle** changed status from "new" to "closed"
