### ISSUE TITLE
Suppress DREAM Fit Results Panel if DREAM not in use (Trac #452)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#586]
ESS Win 7 Ver 3.1.0 Build 124

If you use DREAM and, for whatever reason, close the Fit Results Panel and then choose a different optimizer. When your next fit completes the Fit Results Panel pops back up!

Migrated from http://trac.sasview.org/ticket/452
```json
{
    "status": "closed",
    "changetime": "2015-07-14T09:59:58",
    "_ts": "2015-07-14 09:59:58.205296+00:00",
    "description": "ESS Win 7 Ver 3.1.0 Build 124\n\nIf you use DREAM and, for whatever reason, close the Fit Results Panel and then choose a different optimizer. When your next fit completes the Fit Results Panel pops back up!",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-07-07T17:18:59",
    "component": "SasView",
    "summary": "Suppress DREAM Fit Results Panel if DREAM not in use",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by ajj** [comment]
Trac update at `2015/07/10 21:21:39`: 
* **ajj** changed _comment0 from "On the Mac, the fit results panel is always open, regardless of fitter being used. I assume this is related, but had not considered it a bug ..." to "1436563770535210"
* **ajj** commented:

On the Mac whenever the fit perspective starts, the fit results panel opens. I don't think this is DREAM related as if I close the fit results panel (which is exactly behind the fitting panel, so might not be obvious) and then run a fit with L-M (having not changed the fitter or opened the fit options) then it pops back up on top.

This is new behaviour and is a bit annoying since it contains no useful information.

If the user doesn't close it and doesn't move the fit panel, they probably won't notice as it doesn't pop on top if you haven't closed it.

**Comment by pkienzle** [comment]
Trac update at `2015/07/13 16:12:48`: 
* **pkienzle** changed resolution from "" to "fixed"
* **pkienzle** changed status from "new" to "closed"

**Comment by smk78** [comment]
Trac update at `2015/07/14 09:59:58`: **smk78** commented:

Thing is, the Results Panel doesn't carry any dataset identification or datetime string so if you have previously done a DREAM fit, then changed to something else, there isn't anything to warn you that the information in the Results Panel is now stale.

I'll accept this ticket as closed, but will open a new one to capture the above which I think is a source of confusion.
