### ISSUE TITLE
Rearranging tabs isn't working perfectly (Trac #470)

### ISSUE THREAD

**Issue by mdoucet** [SasView/sasview#604]
If you have multiple tabs in the fit panel and rearrange them, there is no way to bring them back in the same sub-window.

Migrated from http://trac.sasview.org/ticket/470
```json
{
    "status": "closed",
    "changetime": "2018-11-27T18:19:07",
    "_ts": "2018-11-27 18:19:07.126564+00:00",
    "description": "If you have multiple tabs in the fit panel and rearrange them, there is no way to bring them back in the same sub-window.",
    "reporter": "mathieu",
    "cc": "",
    "resolution": "worksforme",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-10-26T20:05:39",
    "component": "SasView",
    "summary": "Rearranging tabs isn't working perfectly",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "butler",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/03/20 22:54:16`: **butler** changed milestone from "SasView 4.0.0" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2017/10/26 11:21:05`: **butler** changed milestone from "SasView Next Release +1" to "SasView 5.0.0"

**Comment by butlerpd** [comment]
Trac update at `2018/09/06 07:54:05`: **butler** commented:

It is actually very hard to do but possible as I recall.  However the point you make: it is not relevant to ESS GUI is appropriate and the question is whether it is worth expending the limited resources on fixing this Wx issue or just wait till QT GUI is out (5.0).  I think the fact that this ticket was placed into the ESS GUI means we opted for the latter.  Question: Does the ESS GUI even allow rearrangement?

**Comment by rozyczko** [comment]
Trac update at `2018/11/21 13:52:38`: **piotr** commented:

Yes, tabs can be rearranged freely in the fitting widget in 5.0. However, what is being meant by "bringing them back in the same subwindow"? Automatic re-arranging to the original order? If so, how is the original order defined?

**Comment by butlerpd** [comment]
Trac update at `2018/11/21 16:00:00`: **butler** commented:

I think we can probably close this.  Just checked in 4.2 in order to explain better and see that it actually seems to works well now in 4.2.  I'm also not sure anybody uses the feature.

So in Wx you can pull a tab out into a new "window" within the fit panel which will then snap to the right, top or bottom depending on which edge you drop it on. You can then have both tabs visible at once (or more).  The problem used to be that if you wanted to move the tabs back into one window as tabs instead of windows, it was nearly impossible to do so.

playing now with 5.0 I don't think that is possible there.  Question is whether that is a necessary feature to carry over.  Given how much it has been used I would argue maybe not.  I guess the one place it would have been useful is to look at fits side by side but I think we already a real estate poor so not sure it was ever going to work that way?  Should we decide at next call whether to remove this feature as a requirement?

**Comment by butlerpd** [comment]
Trac update at `2018/11/27 18:19:07`: 
* **butler** commented:

By general agreement on the Nov 27, 2018 conf call, this is no longer a necessary feature desired for 5.0 and beyond and trying to force that would be a lot of work anyway.  Thus we will move this back to 4.2 and close


* **butler** changed milestone from "SasView 5.0.0" to "SasView 4.2.0"
* **butler** changed resolution from "" to "worksforme"
* **butler** changed status from "assigned" to "closed"
