### ISSUE TITLE
Remove MutiplicationModel.py once replacement from Sasmodels is available (Trac #548)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#680]
Once we can replace !MultiplicationModel with Product from sasmodels, we can remove !MultiplicationModel.py

Migrated from http://trac.sasview.org/ticket/548
```json
{
    "status": "closed",
    "changetime": "2016-10-13T05:01:30",
    "_ts": "2016-10-13 05:01:30.918635+00:00",
    "description": "Once we can replace !MultiplicationModel with Product from sasmodels, we can remove !MultiplicationModel.py",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasModels Redesign",
    "time": "2016-03-21T15:22:10",
    "component": "SasView",
    "summary": "Remove MutiplicationModel.py once replacement from Sasmodels is available",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "pkienzle",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/07/04 16:00:36`: 
* **butler** changed description from "Once we can replace MultiplicationModel with Product from sasmodels, we can remove MultiplicationModel.py" to "Once we can replace !MultiplicationModel with Product from sasmodels, we can remove !MultiplicationModel.py"
* **butler** changed owner from "" to "pkienzle"
* **butler** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2016/08/16 16:46:18`: 
* **butler** commented:

Do not have bandwidth to deal with for 4.0 which is already mega late -- can do at code camp or beyond.  Leaving a high priority but moving to +1


* **butler** changed milestone from "SasView 4.0.0" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2016/09/05 02:52:45`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.1.0"

**Comment by pkienzle** [comment]
Trac update at `2016/10/03 21:08:32`: **pkienzle** commented:

sasmodels/product.py implements the product model as defined in !SasView when a form factor is multiplied by a structure factor.  This could be used directly from sasview.

Rather than using ProductKernel,  we could somehow make ER and VR into derived parameters that can be used in constraint expressions, and use constrained fitting to on a mixture model (sasmodels/mixture.py), with product rather than sum used to mix the models.  This will be considerably more work, and belongs in a separate ticket.
