### ISSUE TITLE
stacked_disks model issues (Trac #551)

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#683]
(a) fails compare

(b) needs unit tests with n_stack > 1

Migrated from http://trac.sasview.org/ticket/551
```json
{
    "status": "closed",
    "changetime": "2016-08-12T13:10:23",
    "_ts": "2016-08-12 13:10:23.606356+00:00",
    "description": "(a) fails compare\n\n(b) needs unit tests with n_stack > 1",
    "reporter": "richardh",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-03-22T19:34:11",
    "component": "SasView",
    "summary": "stacked_disks model issues",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "richardh",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/03/26 17:51:05`: **butler** changed summary from "stacked_disk model issues" to "stacked_disks model issues"

**Comment by butlerpd** [comment]
Trac update at `2016/03/27 15:00:13`: **butler** commented:

n_stack is not a polydisperse parameter in !SasView, yet compare is trying to use it as if it was.  This is probably because it is labelled as volume along with the other parameters needed to compute the volume.  Speaks to separating volume and polydisperse parameters. In the meantime have removed it from compare.  Now however no plots are generated

**Comment by butlerpd** [comment]
Trac update at `2016/03/28 14:00:01`: 
* **butler** commented:

Both points now addressed so closing ticket.


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "new" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2016/08/12 13:10:23`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.0.0"
