### ISSUE TITLE
setup_mac.py reads from obsolete register function (Trac #618)

### ISSUE THREAD

**Issue by wpotrzebowski** [SasView/sasview#750]
It seems that setup_mac.py reads from registry functions in src/sas/sascalc/dataloader/readers/associations.py, which are supposed to be obsolete. The readers should be initialized through read_associations() in associations.py. 

Migrated from http://trac.sasview.org/ticket/618
```json
{
    "status": "closed",
    "changetime": "2017-10-27T11:17:37",
    "_ts": "2017-10-27 11:17:37.731615+00:00",
    "description": "It seems that setup_mac.py reads from registry functions in src/sas/sascalc/dataloader/readers/associations.py, which are supposed to be obsolete. The readers should be initialized through read_associations() in associations.py. ",
    "reporter": "wojciech",
    "cc": "",
    "resolution": "obsolete",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-08-16T06:34:14",
    "component": "SasView",
    "summary": "setup_mac.py reads from obsolete register function",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "",
    "type": "defect"
}
```

**Comment by ajj** [comment]
Trac update at `2016/08/16 13:47:50`: **ajj** changed milestone from "SasView 4.0.0" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2017/10/27 11:17:37`: 
* **butler** commented:

A lot of work has happened since this ticket sas submitted and we (including Wojciech who submitted the ticket) have not experienced any issues recently.  We are thus assuming this has been fixed and closing the ticket.


* **butler** changed resolution from "" to "obsolete"
* **butler** changed status from "new" to "closed"
