### ISSUE TITLE
Add some magnetic datasets to the test data folder (Trac #686)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#815]
We should provide some example magnetic datasets in the test folder

Migrated from http://trac.sasview.org/ticket/686
```json
{
    "status": "assigned",
    "changetime": "2017-10-27T16:37:13",
    "_ts": "2017-10-27 16:37:13.444163+00:00",
    "description": "We should provide some example magnetic datasets in the test folder",
    "reporter": "smk78",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView QA and testing",
    "time": "2016-10-04T15:58:11",
    "component": "SasView",
    "summary": "Add some magnetic datasets to the test data folder",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.3.0",
    "owner": "dirk",
    "type": "enhancement"
}
```

**Comment by ajj** [comment]
Trac update at `2016/10/07 20:04:12`: 
* **ajj** changed owner from "" to "dirk"
* **ajj** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2016/12/20 16:42:05`: 
* **butler** commented:

Moving to 4.2 due to lack of resources to achieve in a time and as not critical to 4.1


* **butler** changed milestone from "SasView 4.1.0" to "SasView 4.2.0"

**Comment by butlerpd** [comment]
Trac update at `2017/10/27 16:37:13`: **butler** changed milestone from "SasView 4.2.0" to "SasView 4.3.0"

**Comment by butlerpd** [comment]
Tagging as PolBeam and moving to 5.1

**Comment by dehoni** [comment]
Attached are some 2D and 1D sector data from 10nm nanospheres in d8-toluene (c_Fe2O3 = 50 mg/ml, ~1 vol%) at an aligning magnetic field of 1.5 T in horizontal direction. The 2D data need renaming otherwise SASview does not recognize them as 2D. The polarised beam data (incoming polarised beam, ie SANSPOL no PA) are from the experiment 5-54-60 at D22 courtesy of Dr. Sabrina Disch, University of Cologne, Germany. According to ILL data policy the data are now open access released under the terms of the Creative Commons license CC-BY.
The results have been published in S. Disch, New J. Phys. **14**, 013025 (2012), doi:10.1088/1367-2630/14/1/013025 and further discussed in her PhD thesis (https://publications.rwth-aachen.de/record/465381). Taking the reported values as starting parameters it should be possible to model the scattering. Be aware, for the nuclear structure one has to take into account micelles composed of remaining oleic acid.

If needed I can hand in also the raw data and the Grasp project used.

**2D data**
[S50_I-_2D.txt](https://github.com/SasView/sasview/files/5103861/S50_I-_2D.txt)
[S50_I+_2D.txt](https://github.com/SasView/sasview/files/5103864/S50_I%2B_2D.txt)
[S50_unpol_2D.txt](https://github.com/SasView/sasview/files/5103866/S50_unpol_2D.txt)

**1D sectors**
[S50_15kG_horizSector_RF-.txt](https://github.com/SasView/sasview/files/5103878/S50_15kG_horizSector_RF-.txt)
[S50_15kG_horizSector_RF+.txt](https://github.com/SasView/sasview/files/5103879/S50_15kG_horizSector_RF%2B.txt)
[S50_15kG_vertSector_RF-.txt](https://github.com/SasView/sasview/files/5103880/S50_15kG_vertSector_RF-.txt)
[S50_15kG_vertSector_RF+.txt](https://github.com/SasView/sasview/files/5103881/S50_15kG_vertSector_RF%2B.txt)

**Comment by dehoni** [comment]
Magnetic-field dependent data are missing. But these can not be analysed with the current magnetic description that has only fixed orientation or at best small angular dispersion.

**Comment by smk78** [comment]
With the data now committed to the repo(s) the outstanding action on this issue is a tutorial on analysing magnetic data, so moving this issue to tutorials.
