### ISSUE TITLE
after copy & paste parameters, "please select parameters to fit" (Trac #742)

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#858]
after copy & paste parameters, "please select parameters to fit" appears when you hit fit, have to deselect and select fitting parameter check boxes.

Migrated from http://trac.sasview.org/ticket/742
```json
{
    "status": "closed",
    "changetime": "2016-10-11T15:22:16",
    "_ts": "2016-10-11 15:22:16.980848+00:00",
    "description": "after copy & paste parameters, \"please select parameters to fit\" appears when you hit fit, have to deselect and select fitting parameter check boxes.",
    "reporter": "richardh",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-10-08T20:12:56",
    "component": "SasView",
    "summary": "after copy & paste parameters, \"please select parameters to fit\"",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "piotr",
    "type": "defect"
}
```

**Comment by RichardHeenan** [comment]
Trac update at `2016/10/09 16:54:27`: **richardh** changed priority from "minor" to "major"

**Comment by RichardHeenan** [comment]
Trac update at `2016/10/09 16:56:31`: **richardh** commented:


After any modifications to a model (e.g. add or remove an S(Q)) the selected "fit" check boxes are ignored?

**Comment by butlerpd** [comment]
Trac update at `2016/10/10 17:35:44`: **butler** commented:

a bit more sleuthing and seems that for parameters that are copied the state of the checkbox is also copied but is not passed to the model so that the model always thinks it is unchecked.  If the parameter is not copied its state is not changed so if checked will be properly seen as checked.

Then there is the problem that if a model is selected with some parameters checked and a new model (either a new one or as a pq*sq any checked parameters are not recognized by the model and pressing fit throws up a "you must select parameters to fit" error.  This is probably a result of the change that all parameters are unchecked by default when choosing a new model.

**Comment by rozyczko** [comment]
Trac update at `2016/10/11 14:28:08`: 
* **piotr** commented:

It looks like wx doesn't update the model on view change and requires refreshing. Should be pretty easy to fix.


* **piotr** changed owner from "" to "piotr"
* **piotr** changed status from "new" to "accepted"
