### ISSUE TITLE
Projects saved in (Mac) 3.1.2 do not open in 4.0 (Trac #795)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#896]
Reported by hmarti18@vols.utk.edu:

Projects saved in Mac version 3.1.2 would not open in 4.0.

User reverted to 3.1.2 and all was well.

This may be fixed in the work Jeff did at the end of Code Camp V towards 4.1 but should be checked.

Migrated from http://trac.sasview.org/ticket/795
```json
{
    "status": "closed",
    "changetime": "2017-02-07T19:05:13",
    "_ts": "2017-02-07 19:05:13.424674+00:00",
    "description": "Reported by hmarti18@vols.utk.edu:\n\nProjects saved in Mac version 3.1.2 would not open in 4.0.\n\nUser reverted to 3.1.2 and all was well.\n\nThis may be fixed in the work Jeff did at the end of Code Camp V towards 4.1 but should be checked.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-10-24T15:36:37",
    "component": "SasView",
    "summary": "Projects saved in (Mac) 3.1.2 do not open in 4.0",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "krzywon",
    "type": "defect"
}
```

**Comment by pkienzle** [comment]
Trac update at `2016/10/24 16:40:57`: **pkienzle** commented:

This will require quite a bit of work.

In addition to finding the equivalent new model you must also update the parameters to the new names, and in some case change the values.  For example (radius, inner_radius) goes to (radius=inner_radius, thickness=outer_radius-radius).  We've already got code to go the other direction which we used to test against sasview 3.x (see sasmodels/convert.py); this needs to be turned into forward conversion code, and used to update the parameters in `perspectives.fitting.pagestate.PageState._parse_state()` after `from_xml()`.

It shouldn't be _that_ hard to do given that we already know all the conversions (except for `raspberry`), but it'll take some time.  Testing could be especially tedious if you do it by hand.  Every model needs to be saved and reloaded to make sure the parameters are converted correctly.  Given the number of models involved, writing a script to do this would be worthwhile.

The reparameterized models with polydispersity may not be translatable.  For example, an outer radius of 100 A with 10% pd will use values in (70, 130).   If the inner radius is 90 A, then setting thickness to 10 A with 100% pd, giving values in (0, 40) gives the same result.  However, if both inner and outer radius are polydisperse at 10% there is no value of thickness pd which will yield the same set of models, with inner in (63, 117) and outer in (70, 130).  If you allow thickness of 67 A to achieve the maximum outer radius when the inner radius is smallest, then the new maximum outer radius will be 184.

Also need to check different polydispersity distributions, 2-D models, and magnetic models are properly saved and restored.   Need to make sure parameter uncertainties are reloaded as well, even for parameters that have changed names.  Don't need to check constrained fits since they weren't able to be reloaded before.

**Comment by butlerpd** [comment]
Trac update at `2016/10/24 17:28:14`: **butler** commented:

Can we get the users file to attache here and use as a test case?  

Jeff did do substantial work on the save project for 4.1 (in fact the whole code camp) and did do things that he thought handled a lot but not all of the old models - probably for some of the reasons Paul says.  Not sure how backwardly compatilbe we can be without getting ourselves in the hole we are in of overly complicated stuff that gets very hard to maitain long term, but we don't want to have users constantly losing stuff every time we make a new release either -- a bit of a balancing act here I guess but if we have the real world example we can see if it works and ask Jeff what the state of play is and what his plans/thoughts were vis a vis Paul Kienzle's discussion above?

**Comment by pkienzle** [comment]
Trac update at `2016/10/24 20:34:11`: **pkienzle** commented:

Sum/product models will require an extra step.  Have to recognize that it is a composition model rather than an old style python custom model, identify the component models, and split the p1_* parameters from the p2_* parameters.  For each p1_/p2_ set, strip the prefix, rename according to the sasview->sasmodels conversion, then add back the prefix.  This may be recursive if it is the sum of sum models for example.

Similarly, S(Q)*P(Q) models will require separation into P(Q) and S(Q) parameters, renaming them separately, then combining them again.  It will be a little different since the parts aren't tagged with p1_ and p2_, but in this case you can look up the S(Q) parameters from the S(Q) conversion table.

**Comment by ajj** [comment]
Trac update at `2016/10/24 21:48:41`: **ajj** commented:

I think the better approach would be to '''not''' do this "transparently" - we should have a conversion routine that users can run their saved projects from 3.1.2 and 4.0 through to convert them to work in 4.1

We have the added wrinkles that people saving 4.0 files also won't be compatible with 4.1 because some model parameter names have changed since 4.0 was released and also 4.1 will have different style composition models.

**Comment by pkienzle** [comment]
Trac update at `2016/10/25 00:41:36`: **pkienzle** commented:

`sasmodels.convert.convert_model(name, pars)` on the ticket776 branch takes an old name and old parameters and returns the new name and new parameters.  If called with a new name it does nothing.  

Note that this does not convert fit ranges or uncertainty in the fitted value, both of which need to be scaled by 1e6 for SLDs.  There are also models which scale by 1e15 and 1e-13.  

Also, the multiplicity is not stored as a parameter, but instead stored as multi factor in the page state.  This is okay except for `spherical_sld`, which has been updated so that core is just another layer, and multi factor needs to be incremented.  Before calling convert `pars['CONTROL']` should be set to multi factor, and on return multi factor should be set to `pars.pop('CONTROL')`.

**Comment by pkienzle** [comment]
Trac update at `2016/11/08 14:27:01`: 
* **pkienzle** changed owner from "" to "krzywon"
* **pkienzle** changed status from "new" to "assigned"
