### ISSUE TITLE
model docs link broken on sasview home page (Trac #798)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#898]
Broken link to model docs on http://www.sasview.org/links.html:

    http://www.sasview.org/docs/user/models/model_functions.html

Migrated from http://trac.sasview.org/ticket/798
```json
{
    "status": "closed",
    "changetime": "2016-10-28T01:55:11",
    "_ts": "2016-10-28 01:55:11.631956+00:00",
    "description": "Broken link to model docs on http://www.sasview.org/links.html:\n\n    http://www.sasview.org/docs/user/models/model_functions.html",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-10-27T15:10:34",
    "component": "SasView",
    "summary": "model docs link broken on sasview home page",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "butler",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/10/27 17:02:30`: 
* **butler** commented:

the above is actually correct (at least now) - however there is another link on the help page which needs changing.


* **butler** changed owner from "" to "butler"
* **butler** changed status from "new" to "accepted"

**Comment by butlerpd** [comment]
Trac update at `2016/10/27 22:46:48`: **butler** commented:

Ok .. looks like two different links to docs on each page- on to docs and one to model docs -- should probably remove model docs specific links since the full docs go directly to user docs and models are at the beginning of that page.  The need for two links is now obsolete

So probably just remove those two links to close the ticket

**Comment by butlerpd** [comment]
Trac update at `2016/10/28 01:55:11`: 
* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "accepted" to "closed"
