### ISSUE TITLE
load project issues (Trac #915)

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#998]
Have found instance of load project not creating proper state of the loaded fits. Attached csd5...  works fine but very similar csd8... where the polydispersity is Schultz instead of Gaussian, appears to load the parameters OK, but the fits are as per the default params for the models. Hitting compute on each of the 3 fit pages (but this does not update plots), then fit on the constraints page restores the expected fit. Hitting just the latter without the computes first, the fit blows up.

Migrated from http://trac.sasview.org/ticket/915
```json
{
    "status": "closed",
    "changetime": "2017-10-23T06:39:46",
    "_ts": "2017-10-23 06:39:46.963919+00:00",
    "description": "Have found instance of load project not creating proper state of the loaded fits. Attached csd5...  works fine but very similar csd8... where the polydispersity is Schultz instead of Gaussian, appears to load the parameters OK, but the fits are as per the default params for the models. Hitting compute on each of the 3 fit pages (but this does not update plots), then fit on the constraints page restores the expected fit. Hitting just the latter without the computes first, the fit blows up.",
    "reporter": "richardh",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2017-04-04T13:35:48",
    "component": "SasView",
    "summary": "load project issues",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "krzywon",
    "type": "defect"
}
```

**Comment by RichardHeenan** [comment]
Trac update at `2017/04/04 13:37:40`: 
* **richardh** changed attachment from "" to "csd5_withSQ_proj.svs"
* **richardh** commented:

csd5 works

**Comment by RichardHeenan** [comment]
Trac update at `2017/04/04 13:38:20`: 
* **richardh** changed attachment from "" to "csd8_withSQ_69ptSchultz_proj.svs"
* **richardh** commented:

csd8 fails to start up nicely, the fits should be good!

**Comment by RichardHeenan** [comment]
Trac update at `2017/04/05 15:19:47`: 
* **richardh** changed attachment from "" to "csd9_twoModels_proj.svs"
* **richardh** commented:

csd9.. has two model versios, M2 swaps to M3 on input, but not in the constraints

**Comment by RichardHeenan** [comment]
Trac update at `2017/04/05 15:20:05`: **richardh** commented:

Another project csd9... attached after, fit page M2 had different model (sphere not core_shell_sphere), but when reloaded this is now M3, but the constraints are as per the original.

**Comment by RichardHeenan** [comment]
Trac update at `2017/04/05 16:46:01`: **richardh** commented:

Simpler project, sph1... After loading project Model line on plot only updates to correct fit if hit "compute" twice.

**Comment by RichardHeenan** [comment]
Trac update at `2017/04/05 16:47:24`: 
* **richardh** changed attachment from "" to "sph1_proj.svs"
* **richardh** commented:

sph1_proj has simpler poly sphere*hard sphere, single data set, plot not up to date after load

**Comment by butlerpd** [comment]
Trac update at `2017/06/15 17:23:02`: **butler** commented:

user Artem Feoktystov reports similar issue:


   It seems like I have found a bug.

   I was fitting 4 curves simultaneously in "Const & Simul Fit" mode. I have set up relation between parameters for the M1, M2, M3 and M4 curves (Model Titles) then ran successfully fits. I saved the project, but when I re-opened it again, the Mx models were in completely another order. I mean the Mx Model Titles were pointing now to another curves. So, I had to re-arrange the constrains by changing numbers at M's in order to come back to the previous (before closing) state.

   And another point:

   when one selects the data sets to be loaded into the !SasView - they appear in alphabetical order in Data Explorer, but once I "Send To" them all to "Fitting" - the FitPageX pages appear to have the curves in a random order. So that the alphabetical order of the data is not preserved in !FitPage numeration.

   I think it might be somewhere here. Can it be that !SasView has different assigned numbers for the models within the current session and svs-file saved later?

   I'm using !SasView 4.1 on Win7 SP1 (64-bit, with all updates).

**Comment by RichardHeenan** [comment]
Trac update at `2017/08/21 14:19:37`: **richardh** commented:

Installed 4.1.2 on Windows 7
If I set up fits to say 3 data sets, with constraints, save the project, then load it inot a new sasview session the order of the models and the order of the data sets in FitPage1, FitPage2 etc is still not being conserved, but likely no-one has had time to look into this bug yet. This messes up the constraints, and indeed they can then reference a parameter that does not exist if I don't have identical models for each FitPage.

Sometimes, but not always, so I cannot yet supply a consistent example, the constrained fit fails to run and error message appears as below.

2017-08-21 15:06:07 : Traceback (most recent call last):
  File "sas\sasgui\perspectives\fitting\fit_thread.pyc", line 82, in compute
  File "sas\sasgui\perspectives\fitting\fit_thread.pyc", line 14, in map_apply
  File "sas\sasgui\perspectives\fitting\fit_thread.pyc", line 11, in map_getattr
  File "sas\sascalc\fit\BumpsFitting.pyc", line 275, in fit
  File "sas\sascalc\fit\BumpsFitting.pyc", line 375, in run_bumps
AttributeError: 'FitDriver' object has no attribute 'fitter'
